ArduPilot/pymavlink

mavutil.py
I am updating MatrixPilot to use the latest mavlink generator for C and Python files. (it's been a while).
Before the enclosed commit, If I run mavlogdump.py on a generic matrixpilot raw log file I get the following errors message with previous MatrixPilot mavlink log files:-
```
Peters-iMac:tools phollands$ ./mavlogdump.py --dialect matrixpilot --no-timestamps /tmp/log.raw 
ERROR LOADING MAVNATIVE - falling back to python implementation
Traceback (most recent call last):
File "./mavlogdump.py", line 113, in <module>
m = mlog.recv_match(blocking=args.follow)
File "/Users/phollands/MatrixPilot/Tools/MAVLink/mavlink/pymavlink/mavutil.py", line 344, in recv_match
m = self.recv_msg()
File "/Users/phollands/MatrixPilot/Tools/MAVLink/mavlink/pymavlink/mavutil.py", line 323, in recv_msg …
```
=> Fix mavlogfile class for generic log files that have no timestamps.

generator/C/include_v2.0/mavlink_types.h
This header is used by C99 source files, which do not
necessarily include &lt;stdbool.h&gt; before including this
header. stdbool.h is needed to define the type 'bool'
that is used in this header. See
https://en.wikibooks.org/wiki/C_Programming/C_Reference/stdbool.h
I need this to be added for the PX4/Firmware project which
doesn't compile anymore after reordering headers (aka, not
having a #include &lt;stdbool.h&gt; anymore before including
this header).
=> Add #include <stdbool.h>

generator/mavgen_wlua.py
Before, both the CRC and Payload fields were ".crc" in the Wireshark filter string definition. Payload is now correctly named ".payload".
=> Payload field of struct is now correctly labeled within the Wireshark filter string

mavutil.py
OFFBOARD mode is interpreted as UNKNOWN.
Changing custom_sub_mode to custom_main_mode in line 1597 solves this issue.
=> mavutil.py: OFFBOARD mode interpretation fix

generator/java/lib/Messages/MAVLinkStats.java, generator/mavgen_java.py
The get%s() one was nasty as it created a new string object on the stack per character operation.
=> Java: Fix up some performance related bugs found by findbugs

generator/java/lib/Messages/MAVLinkMessage.java, generator/mavgen_java.py
Sysid and compid are worth having printed out in toString for debug purposes.
(Not sure what the deal is with the newline at the end of MAVLinkMessage.java, according to git no mater what I did I was either adding or deleting a new line...)
=> Java: Enhance the debug prints to include sysid/compid

tools/mavfft_int.py
we're regularly dropping every 10th accel sample. Need to check whether this is happening at the sensor, or just in the log:
```
sample range:  4382 38370
N samples:  33988
ndeltas:  33987
duration: 37.785 seconds
average sample rate: 899 Hz
mean sample interval:  1.11 msec
std:  342 usec
```
=> WIP: add dropout check to fft plotter

generator/mavschema.xsd
A file attribute would allow easy tracking of the include hierachy when parsing
from any form that doesn't come with the correct file name.
(InputStreams for example, where you can't track what the original name was)
=> Add a file attribute to the XML schema

generator/C/include_v2.0/mavlink_helpers.h
This fixes a parser bug in the mavlink v2.0 parser where we would get a
message flagged as valid when actually the CRC check failed.
The problem was that status->msg_received which was set to
MAVLINK_FRAMING_BAD_CRC got overwritten in the later signing steps.
Found with @bkueng. 
Edit:
Even though signing was not used, what happens is that `rxmsg->incompat_flags & MAVLINK_IFLAG_SIGNED` can be true because it is essentially garbage.
=> generator/C: fix mavlink v2.0 parser bug

tools/mavfft_int.py
*** note that mavfft_int.py assumes that the fast logging option messages ACCn and GYRn contain sample sequence counts in the SampC field. See https://github.com/ArduPilot/ardupilot/pull/5939 **
this overrides the hardwired rates with actual measured sample rates
=> use measured sample rates in mavfft_int

generator/mavschema.xsd
As I wrote in https://github.com/ArduPilot/pymavlink/pull/59#issuecomment-296444133, that change broke the XML validation. It added an attribute referencing a type named file, but none existed. This changes it to the intended line.
=> Fix mavschema.xsd

.travis.yml
Python 3.3 goes [EOL](https://docs.python.org/devguide/index.html#branchstatus) next month so let's shift up one.
=> Python 3.3 end of life

generator/mavgen_java.py
The "MAVLinkPacket" class in the Java implementation always imported the "common" messages and the name of the message definition XML file you generated from.
This was incorrect for two reasons:
- The "common" package may not exist if the message definition XML file does not include the "common.xml"
- If the message definition XML file includes additional message sets they will not be included properly.
This commit fixes both issues.
=> Fixed an issue with the way that the Java Import statements were generated.

tools/mavfft_int.py
__raw_input()__ was removed from Python 3 in favor of __input()__.
=> Define raw_input() for Python 3

generator/C/include_v2.0/mavlink_helpers.h
fix memory overflow on ( len==0 && MAVLINK_MAX_PAYLOAD_LEN < 249 && not(MAVLINK_CHECK_MESSAGE_LENGTH) )
see issue #97
=> C_API_v2.0: skip payload read when len is null ( fix: #97 )

DFReader.py
This is a follow-up on #30 to correct a small bug introduced in there.
When using context managers and the [`with` statement](https://www.python.org/dev/peps/pep-0343/), it's superfluous to call `.close()` on the file-like object.
=> Remove unneeded .close() statements

tools/mavlogdump.py
Adds --show-available -types option.
The types need to be specified to generate a csv file, this PR adds an option that lists them like this:
```
Found message types:
MISSION_COUNT
ATTITUDE
RC_CHANNELS
BATTERY_STATUS
HEARTBEAT
MISSION_CURRENT
RAW_IMU
SCALED_PRESSURE2
MOUNT_STATUS
GPS_RAW_INT
SCALED_IMU2
NAV_CONTROLLER_OUTPUT
VFR_HUD
MEMINFO
HWSTATUS
VIBRATION
STATUSTEXT
AHRS
SENSOR_OFFSETS
COMMAND_ACK
NAMED_VALUE_FLOAT
SCALED_PRESSURE
GLOBAL_POSITION_INT
SYS_STATUS
POWER_STATUS
PARAM_VALUE
SYSTEM_TIME
EKF_STATUS_REPORT
AHRS3
AUTOPILOT_VERSION
SERVO_OUTPUT_RAW
AHRS2
RC_CHANNELS_RAW
```
Signed-off-by: Willian Galvani <williangalvani@gmail.com>
=> mavlogdump: add --show-available-types option

mavutil.py
Without this we rumble on into trying to do things with the port and
return a bodgy failure condition - transport endpoint already in use,
for example
=> mavutil: always raise exception on tcp connect failure

setup.py
The package `future` needs to be added to the `setup_requires` list (i.e., *a string or list of strings specifying what other distributions need to be present in order for the setup script to run*, [source](http://setuptools.readthedocs.io/en/latest/setuptools.html#id8)) in `setup.py`.
The reason is that `future` is needed in pymavlink's installation phase, in `setup.py` itself: `future` is imported by [`mavgen.py`](https://github.com/ArduPilot/pymavlink/blob/master/generator/mavgen.py#L12), which is imported by [`setup.py`](https://github.com/ArduPilot/pymavlink/blob/master/setup.py#L21).
In the past, this has caused some problem with pymavlink installation, e.g. [this issue](https://github.com/ArduPilot/pymavlink/issues/25) and failed builds [like …
=> Add future to setup_requires in setup.py

generator/C/include_v0.9/protocol.h, generator/C/include_v1.0/protocol.h, generator/C/include_v2.0/protocol.h
GCC 8.0.1 warning/error that I got:
```
../../mavlink/include/mavlink/v2.0/common/./mavlink_msg_heartbeat.h: In function ‘uint8_t mavlink_msg_heartbeat_get_type(const mavlink_message_t*)’:
../../mavlink/include/mavlink/v2.0/common/../protocol.h:247:91: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
#define _MAV_RETURN_uint8_t(msg, wire_offset) (const uint8_t)_MAV_PAYLOAD(msg)[wire_offset]
```
=> protocol.h: fix GCC warning: type qualifiers ignored on cast result type

generator/C/include_v2.0/mavlink_helpers.h
Removal of null pointer detection in v2.0 suppressed conveniency invocation to parser like:
`mavlink_parse_char(MAVLINK_BACKHAUL, *tp, NULL, NULL);`
Better to restore.
=> Restore null pointer detection in parser.

tools/mavlogdump.py
When using "--csv_sep ;" the header was still using "," as separator.
Signed-off-by: Willian Galvani <williangalvani@gmail.com>
=> mavlogdump: Make headers use csv_sep when outputting csv

generator/mavgen_java.py
I believe the changes pretty much speak for themselves. The `directory` string is generated elsewhere with `os.path.join`, which uses backslashes as a path separator on Windows.
On a semi-related note, this file has *a lot* of trailing white space that my editor automatically removed, which I had to filter out to make a clean diff.
=> Fix Java package name generation on Windows

generator/mavschema.xsd
Required by mavlink/mavlink#917
=> Added centimetres squared unit (typically used in variance)

generator/mavgen_python.py
When enums/units were moved from XML description to their own attributes the info disappeared from the docs. This adds the information back for pymavlink. 
See #220
=> Add field units and types into generated python message docs

mavutil.py
Before:
[pid 13322] getpid()                    = 13302
[pid 13322] wait4(13306, 0x7f7f4ac4b624, WNOHANG, NULL) = 0
[pid 13322] stat("/etc/resolv.conf", {st_mode=S_IFREG|0644, st_size=337, ...}) = 0
[pid 13322] openat(AT_FDCWD, "/etc/hosts", O_RDONLY|O_CLOEXEC) = 25
[pid 13322] fstat(25, {st_mode=S_IFREG|0644, st_size=658, ...}) = 0
[pid 13322] read(25, "127.0.0.1\tlocalhost\n127.0.1.1\tbl"..., 4096) = 658
[pid 13322] read(25, "", 4096)          = 0
[pid 13322] close(25)                   = 0
[pid 13322] sendto(8, "\375\16\0\0\203\1\1\35\0\0P=\26\0~]nD\0\0\0\0\36\20\313\316", 26, 0, {sa_family=AF_INET, sin_port=htons(9866), sin_addr=inet_addr("127.0.0.1")}, 16) = 26
[pid 13322] getpid()                    = 13302
[pid 13322] wait4(13306, 0x7f7f4ac4b624, WNOHANG, NULL) = 0
[pid 13322] …
=> mavutil.py: mavudp: stop resolving target hostname for every sendto()

generator/mavschema.xsd
Every message should IMO have a description (as suggested by @amilcarlucas here: https://github.com/mavlink/mavlink-devguide/pull/96#discussion_r207462353).
While we're here, are there any other types that really must have a description? I think all enums, enum values, params should have descriptions too. BUT, adding those will break the current common.xml as both enums and enum values are missing descriptions: https://mavlink.io/en/messages/common.html
So if we agree that I'll need to make sure the XML is updated first.
=> Enforces description for messages

examples/bwtest.py, examples/mav2pcap.py, generator/mavgen_cs.py, generator/mavgen_python.py, mavextra.py, mavparm.py, mavutil.py, mavwp.py, rotmat.py, tests/test_fgFDM.py, tests/test_mavexpression.py, tools/magfit_delta.py, tools/mavgraph.py, tools/mavsummarize.py, tools/mavtomfile.py
PEP8 [suggests](https://docs.quantifiedcode.com/python-anti-patterns/readability/comparison_to_none.html) to use `is None` to compare a value to `None`, instead of the equality operator.
This has an important consequence in the `parse_char` function in `mavgen_python.py`. When profiling a DroneKit-based application with yappi, I noticed that a lot of computation time (8.7%) was spent in the `__eq__` method of MAVLink message object.
After running my application for a few minutes, the profiler recorded 1.9 million calls to `MAVLink_attitude_message.__eq__`.
That was weird!
The problematic code resides in the [`parse_char` function](https://github.com/ArduPilot/pymavlink/blob/b4d048f16422ebe482593ff7ad0e35baaa92b833/generator/mavgen_python.py#L558):
```python
if m != None: …
```
=> Simplify comparisons with None, True, False

generator/mavschema.xsd
As discussed in mavlink/mavlink#1009 we have to add centiseconds as SI unit.
@amilcarlucas Is this all I had to change?
=> Add centiseconds as SI_Unit

generator/C/include_v2.0/mavlink_helpers.h
Likely fine in this case (checksum is the first field), but it's easy enough to avoid entirely and enable the warning. `-Waddress-of-packed-member` is on by default in GCC 9 and Clang 4.
In file included from ../../mavlink/include/mavlink/v2.0/common/mavlink.h:32:
In file included from ../../mavlink/include/mavlink/v2.0/common/common.h:30:
In file included from ../../mavlink/include/mavlink/v2.0/common/../protocol.h:75:
../../mavlink/include/mavlink/v2.0/mavlink_helpers.h:247:25: fatal error: taking address of packed member 'checksum' of class or structure '__mavlink_message' may result in an unaligned pointer value [-Waddress-of-packed-member]
crc_accumulate_buffer(&msg->checksum, _MAV_PAYLOAD(msg), msg->len);
^~~~~~~~~~~~~
1 error generated.
=> mavlink_helpers.h eliminate possibility of unaligned memory access

generator/mavschema.xsd
MAV_CMD param values are current indicated as reserved using a tag content of "Reserved" or "Empty" (if no param is defined, this is also assumed to be reserved). The default value is typically default set by Mission Planner and QGC as 0, though sometimes a user will indicate default value of NaN in the description. 
> **Note** The default value is a bit of a pain for params, because once it is set to 0 or NaN the param can't be reused for a real param where the default value means anything other than "unchanged". Big discussion of reasons [here](https://github.com/mavlink/mavlink/issues/1050).
This PR adds `reserved` attribute to allow a param to explicitly be marked as reserved, and `default` to allow a default value (along with enabling `NaN` as a possible default).
@amilcarlucas …
=> mavschema: Add default and restricted attributes to params

generator/C/include_v1.0/mavlink_helpers.h, generator/C/include_v2.0/mavlink_helpers.h
This partially fixes the in-source docs for `mavlink_parse_char()` and friends in the 1.0 and 2.0 generator - the example used incorrect names for parameters  and did not pass in the status variable. 
The description of the problem is in https://github.com/mavlink/mavlink/issues/1086
The issue has a separate comment below which I believe is invalid - @peterbarker can you confirm that the assignments of these are in `mavlink_frame_char_buffer()` (which is called by  `mavlink_parse_char()`).
> Some members of mavlink_status_t are never assigned - for example `msg_received`, `buffer_overrun`, `parse_error` (this is very misleading!). Value from `parse_error` is assigned to `packet_rx_drop_count` - https://github.com/mavlink/c_library_v2/blob/d240d0986710045663894aebcea89e71ce981ee4/mavlink_he …
=> mavlink_helpers: Tidy parser example

generator/swift/README.md
As discussed in https://github.com/ArduPilot/pymavlink/pull/29
=> MAVLink Swift: Add initial README.md in generator/swift

setup.py
The qgroundcontrol.org link still exists, but all content is migrated or migrating to https://mavlink.io/en/
=> Update to new link for MAVlink resources

generator/mavgen.py
The toolchain only supports including 1 level of dialect `include` nesting. This PR allows include files to be nested up to 5 levels deep (but will stop earlier if no new files are detected).
Current set of dialect files are unchanged by this.
=> Add support for more than 1 level of dialect inclusion

generator/mavparse.py
Currently mavlink routing doesn't work on this field so everyone sees it.
=> mavparse.py: understand MANUAL_CONTROL target system field

generator/C/include_v2.0/mavlink_helpers.h
@peterbarker here's another one. https://github.com/ArduPilot/pymavlink/pull/267
=> mavlink_start_checksum() eliminate possibility of unaligned memory access

generator/mavgen_wlua.py
before:
after:
When analyzing a packet in Wireshark, evey field should be linked to a slice of the hex dump. This already happens with most of the fields, it does not happen with the version field.
This PR fixes the problem and links the version byte to the corresponding slice of the hex dump.
=> mavgen_wlua: link version byte to corresponding hex dump

generator/mavgen_wlua.py
before:
after:
Message ids of v2.0 frames are parsed in a completely wrong way, consequently payloads are not identified and frames are not displayed correctly.
Message IDs are saved in up to 3 bytes (24 bits) (1 byte in v1.0, 3 bytes in v2.0).
What the original author did:
* take the 1st byte, right shift by 8, i.e. 255 >> 8, always resulting in zero.
* take the 2nd byte, right shift by 16, i.e. 255 >> 16, always resulting in zero.
* take the 3rd byte, summing all three up and putting the result in a byte (mess is complete).
What i did:
* take all 3 bytes together, parse them as a single 24bits, little endian, unsigned number
* put the result in a uint24.
PS: the Wireshark Lua dissector has a huge quantity of bugs, and it's a pity since it could be a good entry point for people who wants …
=> mavgen_wlua: fix parsing of v2.0 message ids

generator/mavgen_wlua.py
same as #279 but for the message id field.
=> mavgen_wlua: link message id to corresponding hex dump

generator/CPP11/include_v2.0/message.hpp
In message.hpp:106 a `std::stringstream` is created, but `<sstream>` was never included.
=> message.hpp: added missing include

generator/mavgen_python.py
This broke MAVProxy under Python3, see this issue: https://github.com/ArduPilot/MAVProxy/issues/600
=> fix MAVLink_bad_data being initialized with str instead of bytearray

generator/mavparse.py
XML definition files can now declare command params as reserved and define a default value of 0 or NaN. If a param is not declared it is assumed to be reserved with default of zero.
What this PR does is implement that behaviour and generate improved docs:
- adds a numeric prefix (e.g. **3. Param description**) for all `param` value descriptions. This makes it much easier to work out what text maps to which param, and makes it clear that you're in a param even if it has no description.
- adds standard text for reserved values
- Creates "reserved" params for index values that were not declared in XML. This improves docs, but also means we can remove all reserved params from XML if we want. 
The change is in the stored description in the parser, so will flow to all outputs.
It doesn't …
=> Support reserved/default params in generated libraries

generator/mavgen_wlua.py
This PR adds support for interpreting truncated MAVLink 2.0 packets where the trailing zero bytes are omitted in order to reduce the packet size.
The PR also includes the changes authored by @gswly in #279, #281 and #284 (thanks a lot!). In order to track authorship properly, I would advise merging #279, #281 and #284 first; then I can rebase my PR on the then-current master revision.
=> mavgen_wlua: add support for interpreting truncated MAVLink 2.0 packets

DFReader.py
Essentially a partial revert of fc57c0943a9a6b03d18ef801d256b95d43cd3ff6
I'm pretty sure the original patch is complete bogus - doing an encode rather than a debug...
=> DFReader.py: partial fix for string decoding issue

DFReader.py, mavutil.py
Knowing the previous type for a skipped message is very useful for working out how logs are corrupted.
=> Improve skip debug

generator/C/include_v2.0/mavlink_helpers.h
In issue #169 a couple of NULL checks were added preventing a second message or status object from being required when running mavlink_frame_char_buffer in the C library. In two places a memcpy was run with the second message as a destination without checking it exists.
=> Null checks on C helper function mavlink_frame_char_buffer

generator/mavgen_wlua.py
before:
after:
This PR allows the Wireshark plugin to parse and display two fields that were added in Mavlink v2.0:
* incompatibility flag
* compatibility flag
These are currently skipped. In particular, adding the incompatibility flag is the first step in implementing signature parsing (which is also missing).
=> mavgen_wlua: add missing v2.0 fields

generator/mavparse.py
This breaks MAVProxy's waypoint display as it string-matches against
this description.
The value should be available as separate metadata anyway so any user of
the metadata should be able to synthesise this themselves.
@hamishwillee https://github.com/ArduPilot/pymavlink/pull/269/files#diff-47dc7d87fdc00f28b7816950fba41176R162 added this line.  I wish to remove it.  Was this vital for something you were doing?
=> mavprase.py: stop magically prefixing descriptions with their index

mavutil.py
avoids using mtype when it isn't set
=> mavutil.py: skip unrecognised markers when initting arrays

DFReader.py
timestamps for Python3 are 18 hours off without this.
Python3 presents a float when two integers are divided rather than an integer as in Python2.
=> DFReader: correct python3 float/int issue for timestamps

generator/mavparse.py
This reverts part of a change my commit https://github.com/ArduPilot/pymavlink/commit/2e19ed5dd8ef60dbf07c0571d4beb8e2c552cdae 
Basically I did not understand that the parser gets the param description in chunks and assembles them. As a result a small percentage of param descriptions got truncated.
For example, in asluav.h
This fixes that errors.
=> Fix occasional truncate params

mavparm.py
=> mavparm: exclude MIS_TOTAL from being loaded from files by default

mavutil.py
added flight mode 24 ZIGZAG to mavutil.py to resolve the following issue. 
#332
=> Add flight mode 24 ZIGZAG to mavutil

tools/mavlogdump.py
```
pbarker@bluebottle:~/rc/pymavlink(pr/mavlogdump-profile)$ mavlogdump.py --profile -q /tmp/00000014.BIN 
Clock type: CPU
Ordered by: totaltime, desc
name                                  ncall  tsub      ttot      tavg      
...py:587 DFReader_binary.recv_match  126..  5.246718  60.71140  0.000048
..er.py:548 DFReader_binary.recv_msg  126..  3.190012  54.26146  0.000043
..py:805 DFReader_binary._parse_next  126..  15.23515  51.07469  0.000040
..er.py:551 DFReader_binary._add_msg  126..  8.371578  30.08962  0.000024
..r.py:541 DFReader_binary._set_time  126..  5.231683  18.85557  0.000015
..erClock_usec.set_message_timestamp  126..  5.240827  12.28539  0.000010
..mavutil.py:1613 mavlink_connection  1      0.000045  7.248892  7.248892
..er.py:647 DFReader_binary.__init__  1      0.000065 …
```
=> mavlogdump.py: add --profile using yappi

.travis.yml, generator/mavgen.py, generator/mavgen_typescript.py
The current JavaScript implementation does not seem to be actively maintained.
MAVLink2 is not supported and type definitions (for users using TypeScript) are not provided.
I built a library (https://github.com/ifrunistuttgart/node-mavlink) which is able to parse/pack MAVLink1 und 2 messages and handshake the MAVLink version according to https://mavlink.io/en/guide/mavlink_version.html#version_handshaking.
The library currently does not support message signing.
This pull request extends the ability of mavgen to generate TypeScript classes which can be used with this new library. The generated classes can be transpiled into JavaScript, if needed.
=> Adding generator for TypeScript (JavaScript) with MAVLink2 support

generator/mavgen_wlua.py
As shown in the [simulation section of devguide](https://dev.px4.io/en/simulation/), the PX4 also transports data on 14580 UDP port to communicate with external developer APIs by default.
=> Add a port in udp dissector in mavgen_wlua.py

.travis.yml, DFReader.py, mavexpression.py
this allows for graphs like this:
graph RFND[0].Dist RFND[1].Dist
The instance field names come from FMTU msgs in DF logs. For mavlink we'll need to add some XML markup for instance vars
=> support instance variable expressions in DF logs

generator/mavgen_python.py, tests/test_trim.py
Built on top of https://github.com/ArduPilot/pymavlink/pull/347 as it can't be easily tested without that.
Depending on Python version (and, I think, codepath), we may be passed in `bytes` as our payload - and using `chr()` to look into that doesn't work.
Similarly for signature checking - casting to string and taking a subset doesn't work well under Python3, so if we are passed `bytes` in then compare directly.
=> Fix signature checking under Python3

mavutil.py
This was never going to be IOError
=> mavutil: correct type of exception being caught

generator/C/include_v2.0/mavlink_helpers.h
When parsing and discovering a big enough (and possibly invalid) msgid, we ended up accessing the last + 1 element of mavlink_message_crcs.
This was found by fuzz testing against mavlink_parse_char with address sanitizer enabled.
=> generator: fix off-by-one in mavlink_get_msg_entry

generator/C/include_v2.0/mavlink_helpers.h
Since MAVLink 2 we can have message IDs > 256 and we should probably look up the message length in the mavlink_msg_entry dict instead.
Fixes #145.
=> generator: fix message length table overflow

mavutil.py
This allows this file to be used by dronekit-python, MavRos and other similar software.
I will contact the other commiters to this file per e-mail, but I would like to get the OK from the reviewers here first. The full list is bellow, it it be updated with the answers from the devs.
=> Change mavutil.py license from GPLv3+ to LGPLv3+

generator/mavgen_swift.py, generator/swift/MAVLink.swift
Hello,
this PR contains two features for Swift:
- introduces Swift 4.2 support with minimal changes to the code
- introduces bitmask support
and has the following side-effects:
- code now can be built on latest XCode (10.1+)
- more messages are being decoded without errors (like Heartbeats)
Some enumerations are replaced with bitmasks (implemented using standard OptionsSet protocol), because enum type in Swift is incompatible with bitwise operations.
=> mavgen_swift.py: Swift 4.2 with Bitmask support

generator/gen_js.sh, generator/javascript/.eslintrc.json, generator/javascript/package.json, generator/javascript/test/mavlink10.js, generator/javascript/test/mavlink20.js, generator/javascript/test/message10.js, generator/javascript/test/message20.js, generator/mavgen_javascript.py
As the title suggests, this PR patches the Javascript generator so it can generate Mavlink 2.0 messages.
Note it doesn't support signed packets at this time.
Unit tests in the ./generator/javascript/tests directory have been updated and all pass.
Tests can be run via:
```
cd ./generator/javascript
npm install
npm test
```
Also tested with latest APM with no issues.
Fixes #96
=> Generator: Add Mavlink 2.0 support for Javascript

generator/mavgen_cpp11.py
This is the fix for #362. I closed the other one, because my branching was not clean.
@tridge Please review.
=> Fix for bug in CPP11 generator MESSAGE_ENTRIES initialiser list

generator/javascript/package.json, generator/javascript/test/mavlink10.js, generator/javascript/test/mavlink20.js, generator/javascript/test/message10.js, generator/javascript/test/message20.js, generator/mavgen_javascript.py
A few patches for the Javascript generator:
-Allow Mavlink1 and Mavlink2 decoders to be run simultaneously
-Cleanup of unneeded "if" statements
This required many (mostly internal) variable re-names, hence the large diff for these commits.
The unit tests all still pass.
=> Javascript Generator updates

DFReader.py, generator/mavgen_python.py
This is a mav.tlog which shows the decode errors.  One for Python3, one for Python2.  Renamed for github.
[mav.txt](https://github.com/ArduPilot/pymavlink/files/3981978/mav.txt)
=> More unicode decode fixes

mavutil.py
We assume these messages are longer than the loop condition accounts for
on the lines following this patch.
File "/home/pbarker/.local/lib/python2.7/site-packages/pymavlink-2.4.3-py2.7-linux-x86_64.egg/pymavlink/mavutil.py", line 1417, in __init__
self.init_arrays(progress_callback)
File "/home/pbarker/.local/lib/python2.7/site-packages/pymavlink-2.4.3-py2.7-linux-x86_64.egg/pymavlink/mavutil.py", line 1463, in init_arrays
mtype = u_ord(self.data_map[ofs+15]) | (u_ord(self.data_map[ofs+16])<<8) | (u_ord(self.data_map[ofs+17])<<16)
IndexError: mmap index out of range
=> mavutil: add separate range check for mavlink2 messages

tools/mavfft_isb.py
- use hanning windows on the input
- overlap input frames by 50% and use welches method to cover hanning losses
- convert output to power spectral density normalized by NEBW
- change scaling and labels for accel and gyros to m^2/s/s/Hz and d^2/s/Hz linerized PSD
See https://holometer.fnal.gov/GH_FFT.pdf for a description of the techniques used
Before:
After:
=> mavfft_isb: update to reduce artificial noise in output and make graphs comparable

generator/C/include_v2.0/mavlink_conversions.h
Modern compilers might throw a warning due to the implicit increase in precision. The explicit cast (in C syntax to not force C++ for MAVLink library adopters) tells the compiler that this is intentional. We store as an intermediate double to ensure that compilers use full double precision for the operation.
=> Fix compile warnings in mavlink_conversions.h

DFReader.py
Allows us to continue in the face of mildly corrupt logs
=> DFReader.py: continue parsing if a bad header is received

generator/mavschema.xsd
as been discussed on [adding bitmask="true" for enums #1316
](https://github.com/mavlink/mavlink/pull/1316)
=> Adding bitfield option to enum, to indicate multi bits enum

generator/mavgen.py, generator/mavgen_lua.py
This is the basis of a generator for the use with Lua scripts. There are some enhancements that may be made in the future, but it does work. It generates an encode function which can decode the current version of a `mavlink_mesage_t` buffer, and en encode which generates the packed MAVLink buffer needed for `finalize_chan`.
=> Add support for generating Lua 5.3 code for use with ArduPilot

DFReader.py
Some places take a reference to the old array, holding onto old data
when they shouldn't have it.  They can copy.copy it if they really want
it.
Also correct parsing of instance-number-containing fields
=> DFReader: clear message dictionary rather than replacing it

generator/mavschema.xsd
There was no unit for power, added Watt since this seems the most likely unit to be working with in drones. I plan on using it in a future pr
=> Add Watt to list of units

mavutil.py
This may allow us to sunset some really nasty code in ArduPilot which
acks a message which is not a command_long or command_int.
=> mavutil: use command_long for change modes for ardupilot

mavutil.py
This breaks reboot-to-bootloader
This compat code is almost a decade old.
=> mavutil: stop double-rebooting

.travis.yml
The version of Ubuntu used in TravisCI needs to be updated in order to use a modern version of nodejs.
Currently, the nodejs tests are failing with the same error over as https://github.com/mavlink/mavlink/issues/1404.
=> CI: Update build environment

generator/mavschema.xsd
The mavschema currently as grams but not the SI unit kg so this PR adds it.  I plan to use this in a new WINCH_STATUS message that must report the "tension" (i.e. weight on the line).
I have no tested this because I really don't know how it can be tested.  Still, I think it must be safe.
=> generator: add kg units

generator/C/include_v2.0/mavlink_types.h
Fix visual studio warning `C4819: The file contains a character that cannot be represented in the current code page`. It makes errors while building AirSim.
=> generator: fix non-ASCII character

generator/mavgen.py, tests/generation/child.xml, tests/generation/grandchild1.xml, tests/generation/grandchild2.xml, tests/generation/inbred.xml, tests/generation/mixin.xml, tests/generation/mixiner.xml, tests/generation/root.xml
This supersedes #338 and #339. It updates @olliw42 recursive nesting code so I hope it can be merged. #339 will be closed.
Changes w.r.t 338.
1. Removes the changes to default mavlink version etc (were just debug changes that hadn't been cleaned up)
2. Comments out the success-path debug print statements. The fail case statements stay (e.g. indicating for example, unresolvable inclusion)
3. Removes the test xml from the tree. 
@peterbarker I have taken the time to convince myself that this code works. I have also run both Ollie test code and some of my own for both c and Python. The only differences are those that are expected - ie it fixes up the parent dialect headers with the CRCs etc of the nested dialects.
I have not included the test xml because I'm not sure where it would make …
=> mavgen.py: correct handling of includes (updated)

generator/mavgen_python.py
The current generator uses a relative path from the directory `dialects/v<X>` to look for `mavcrc` module in the `generator` module. As a result, any custom generated files need to be placed in the `pymavlink` sources.
With this PR, the generated file can be placed inside the module of the user's choice.
=> Use absolute import path in file generated by mavgen_python

generator/mavcrc.py
https://docs.python.org/3.9/library/array.html#array.array.frombytes
From [What’s New In Python 3.9](https://docs.python.org/3.9/whatsnew/3.9.html#removed))
> array.array: tostring() and fromstring() methods have been removed. They were aliases to tobytes() and frombytes(), deprecated since Python 3.2.
Swiped from https://github.com/ArduPilot/pymavlink/pull/449/files
=> array.array.fromstring() was removed in Python 3.9

DFReader.py, generator/mavgen_python.py, generator/mavparse.py, generator/mavschema.xsd, mavutil.py
This allows for array indexing of mavlink messages, so that array syntax can be used for messages like BATTERY_STATUS which have an instance field
=> Add support for instance field markup in mavlink XML

examples/mavtest.py
This doesn't actually make the thing work; there's some signing weirdness going on in Python3; key needs to be handled differently.
=> examples: fix a couple of Python3 problems in mavtest.py

examples/mavtest.py, generator/mavgen_python.py
mavgen_python.py has a template for MAVLink.check_signature().
Modified that method's python3 detection to check for
class 'bytearray' as well as class 'bytes'. This fixes python3
decoding of signed messages.
Also changed examples/mavtest.py to pass a bytearray for the
secret key instead of a string. This is required to send
a signed message using python3.
=> Fix decoding of signed message on python3.

generator/C/include_v0.9/mavlink_types.h, generator/C/include_v1.0/mavlink_types.h, generator/C/include_v2.0/mavlink_types.h
For cases where more than 4 mavlink channels are required, the mavlink_channel_t does not match. Therefore, I suggest that the enum needs to be provided separately if the default channel number is not used.
=> generator: mavlink_channel_t with correct length

generator/mavschema.xsd
UAVCAN and ArduPilot AP_EFI use cubic centimetres per minute.  The mavlink message is defined as grams/minute, however is packed by AP_EFI as cm^3/min.  This adds necessary units to the schema so I can fix the mavlink message.
Ref: 
https://github.com/ArduPilot/ardupilot/blob/8561f5239d4bc10424e4bfe69ad69dfbdd7c5cc9/libraries/AP_EFI/AP_EFI.cpp#L128
https://github.com/UAVCAN/public_regulated_data_types/blob/c043498eacfe90a56e3246d4c2e4ae81aad13082/uavcan/equipment/ice/reciprocating/1120.Status.uavcan#L165
https://github.com/ArduPilot/mavlink/blob/ed340a4646dfdd873db1430db0b30a0c2ac9b6e3/message_definitions/v1.0/common.xml#L4932
Thanks to Maarrk in the ardupilot discord for identifying this.
=> add units required to align EFI_Status mavlink message with UAVCAN v0

generator/mavgen_javascript.py
This particular fix was found because the 'npm test', test suite was failing on the very special test case of 'zeroed extensions'  and 'non-zeroed extensions' that were introduced a few weeks back.
=> Generator:   fix JS bindings so that they properly trim zero's again.

generator/C/include_v0.9/checksum.h, generator/C/include_v1.0/checksum.h, generator/C/include_v2.0/checksum.h, generator/CS/common/Mavlink.cs, generator/javascript/test/mavlink10.js, generator/javascript/test/mavlink20.js, generator/javascript_stable/test/mavlink10.js, generator/javascript_stable/test/mavlink20.js, generator/mavcrc.py, generator/mavgen_java.py, generator/mavgen_javascript.py, generator/mavgen_javascript_stable.py, generator/mavparse.py, generator/swift/MAVLink.swift, mavutil.py
The description of the CRC does not seem to match the implementation.
The description specifies X.25, however, the code implementing the CRC check does not do the final xor out operation.
This means the result is actually the same as CRC-16/MCRF4XX.
I found this a while back trying to implement it using a table, and then stumbled on the same observation here:
https://discuss.px4.io/t/mavlink-crc-computation-standard-in-mavlink-1/5962
The difference between X.25 and MCRF4XX is just the last xor step:
X.25:
width=16 poly=0x1021 init=0xffff refin=true refout=true xorout=0xffff check=0x906e residue=0xf0b8 name="CRC-16/IBM-SDLC"
MCRF4XX:
width=16 poly=0x1021 init=0xffff refin=true refout=true xorout=0x0000 check=0x6f91 residue=0x0000 name="CRC-16/MCRF4XX"
This is based on: …
=> Fix CRC algorithm documentation

generator/mavgen_c.py
This simple PR does this:
When one is generating the C files, the files which are included in a .xml file via a `<include>` are included in the dialect main header file via a `#include`. This PR ensures that path included via the `#include` is of the form "../dialect/dialect.h".
Why:
Currently, a new dialect needs to be added by creating a new dialect.xml file and placing it into the subfolder message_definitions/v1.0/. This is good and simple for those dialect owners which got the pleasure to have their dialect.xml files being added to the official mavlink git repository.
But for any other users this is quite painful. A git-ish way would be to fork the mavlink repo, create a branch with ones dialect.xml added, and then to submodule to this branch in the main project repo. What a pain. A …
=> Use os.path.basename() for include base

generator/mavgen_cpp11.py
Per the [MAVLink XML schema guide](https://mavlink.io/en/guide/xml_schema.html) relative include paths in message dialect definitions should be supported. ie:
```xml
<include>../mavlink/message_definitions/v1.0/common.xml</include>
```
is a valid include in a message definition file.
However, the C/Cpp generators currently take the whole path from an include tag and place it in an include as shown:
```c
#include "../../mavlink/message_definitions/v1.0/common/../mavlink/message_definitions/v1.0/common.h"
```
This PR modifies mavgen_c and mavgen_cpp11 behavior to agree with the schema guide and allow relative includes. It does this by stripping any path components off the base include string before adding it to the include list. This in turn generates the expected include of :
```c
#include …
```
=> C/Cpp Generator support relative include paths in xml definitions

generator/C/include_v2.0/mavlink_sha256.h
Fixes #489 
Removed all the single-letter macros defined in mavlink_sha256.h and inlined the original definitions at the use site.
Per the issue description, this avoids macro conflicts when using the C mavgen library in an Arduino-like context.
=> Fix conflicting c macro

tools/serial_control_to_shell.py
Gates from serial_control messages to a shell
Absolutely no security.
Takes a pymavlink connect string and anything which is pointed at its serial device port gets treated as shell input.
=> tools: add serial_control_to_shell

mavutil.py
We're doing some experimentation on vehicle types and vehicle modes. However, the hard-coded map of vehicle type to mode name makes this difficult, as it prevents us from easily using MAVProxy for testing.
This PR allows the user to create a `ap_custom_mode_map.py` file that contains a custom mode mapping and have it loaded when `pymavlink` is initialised.
=> mavutil: Allow for custom mapping of vehicle modes

generator/mavschema.xsd
The XML schema that validates mavlink dialect XML files specified that message
IDs were unsignedShorts, thereby restricting them to 16-bit values. However,
mavlink 2 message IDs are 24-bit values. This commit adds a custom 24-bit
message ID type to the schema to allow for validation of the full 24-bit range
of message IDs.
=> Fixing mavlink message ID schema type.

generator/mavgen_python.py
The helper function `to_string` appeared in two generated classes, and it doesn't even operate on the object. So I moved it to module scope. While at it, I changed the final loop cutting one character at a time to instead iterate over the sequence; shouldn't change the outcome.
=> mavgen_python: DRY, move to_string to module scope

tools/mavlogdump.py
This is a change to directly output .mat files rather than rearranging first. 
Currently you get lots of cells and labels:
With this change you get friendly structures with correctly named values:
This results in a format that is different to what you get with MP, but it is also much nicer. 
I guess we might want to make it optional if anyone is particularly attached to the old format.
=> Tools: mavlogdump: do not rearrange .mat before exporting

generator/CPP11/include_v2.0/msgmap.hpp
This should fix compilation on osx (see https://github.com/mavlink/mavros/issues/851)
=> Cross-platform include of endian.h

tools/magfit_WMM.py
The fitting should be done in the autopilot sensor frame of reference, not the body frame. Otherwise when operating close to +-90 pitch the pitch angle in the message will exceed +-90 deg which results in the sign of the predicted Z filed being flipped. Below are comparison fit results  from a tailsitter log with 
AHRS_TRIM_X      0.008438
AHRS_TRIM_Y      -0.042119
AHRS_TRIM_Z      0.000000
Before:
Current function value: 41.3713362683
Iterations: 50
Function evaluations: 456
Gradient evaluations: 50
After:
Current function value: 6.82827669857
Iterations: 53
Function evaluations: 488
Gradient evaluations: 53
=> Correct magfit_WMM.py to account for AHRS_TRIM

DFReader.py
On Py3:
Before:
```
1970-01-01 10:00:02.00: NANS {f : qnan, d : qnan, bf : qnan, bd : qnan}
```
After:
```
1970-01-01 10:00:02.00: NANS {f : qnan, d : qnan, bf : nan, bd : nan}
```
Py2 was not broken
=> DFReader.py: fix qnan detection under Python3

mavutil.py
The seek will take you past the end of the file; the read will return a
zero-length string, the struct.unpack gets shirty when you pass it a
zero-length string
=> mavutil: correct parsing of truncated tlogs

generator/javascript/local_modules/jspack/README.md
https://github.com/codespell-project/codespell
=> Fix a typo discovered by codespell

.github/workflows/test.yml
https://devguide.python.org/#status-of-python-branches v.s.
https://devguide.python.org/devcycle/#end-of-life-branches
=> Test on the current versions of Python

DFReader.py, generator/CS/MavlinkUtil.cs, generator/javascript/test/mavlink10.js, generator/javascript/test/mavlink20.js, generator/javascript_stable/test/mavlink10.js, generator/javascript_stable/test/mavlink20.js, generator/mavgen_cpp11.py, generator/mavgen_cs.py, generator/mavgen_javascript.py, generator/swift/Tests/MAVLinkTests/DataExtensionsTests.swift
Split from https://github.com/ArduPilot/pymavlink/pull/559/commits
=> Fix typos discovered by codespell

generator/mavgen_java.py
Maybe I am missing something, but that surprised me. Typically this means that doing `message.unpack(); message.pack()` changes the sysid/compid, and I don't really see a reason for it :thinking:
=> Don't hardcode sysid and compid when packing

generator/C/include_v2.0/mavlink_helpers.h
The bitfield packing in mavlink_message_t behaves differently on gcc and windows compilers such as VS2019. This difference caused the mavlink_signature_check function unable to verify signature when built with VS2019. Update the mavlink_signature_check code to not depend on the bitfield packing behavior.
=> Update mavlink_signature_check code to be compiler agnostic

mavutil.py
The inherited close() method from the mavlogfile class only closes the file object. However, the mmap object also keeps a handle on the file, which prevents it from being deleted or opened in read mode even after we call close() This commit closes both the file object (by calling the super method) and the mmap object (directly), ensuring that all handles are freed.
=> Close the mmap object

tools/magfit_WMM.py
This adds the option to save a param file and/or plot. Goal being to reduce the pain of mag-fitting several logs. 
My changing of the file extensions is somewhat clunky, `.BIN` rather than `.bin` would break it. Basically I'm not very familiar with python.
=> Tools: magfit_WMM: add option to save plot and param file

DFReader.py, mavutil.py
Adds blimp vehicle and its mode list to pymavlink so that MAVProxy can show the correct modes. 
Also needs the vehicle to be added in MAVProxy, see MAVProxy PR #925.
=> Add Blimp modes

tools/mavfft_isb.py
Two features being added to mavfft_isb.py in two seperate commits.
1) Add option to be able to choose which axis to be able to plot (defaults to all).  Example:
2) When doing multi file analysis, add the file name to the legend.  Example:
=> Mavfft add option to choose axis and add file name to legend 

DFReader.py, generator/mavgen_python.py
Closes https://github.com/ArduPilot/pymavlink/issues/587
Tested DFReader.py using mavlogdump
Tested signing using mavproxy and SITL.
Tracker's autotest sute also passes with these changes
=> Use tobytes instead of tostring on arrays in Python3

mavutil.py
The reasoning behind this is that I had multiple simple services using endpoints in mavproxy and each of them required their own endpoint or they couldn't run in parallel. With multiple endpoints on a Raspberry Pi the cpu usage got very high. This saves cpu and bandwidth by allowing multiple connections to an endpoint and only sending data to active clients.
It allows multiple services/clients to share the same endpoint. The clients time out after 3 seconds.
There's an exception for the case when there's only one client left. This is never "disconnected" in order to keep the current behavior. 
Tested with https://github.com/ArduPilot/MAVProxy/pull/944
=> [proposal] mavutil.py: support multiple clients with a timeout for udpin

generator/mavgen_c.py
The C generator assigns to each nested dialect an increasing `MAVLINK_THIS_XML_IDX`. In the mavlink.h at each level it defines the same value of `MAVLINK_PRIMARY_XML_IDX` and uses the comparison to decide if it should define the arrays `MAVLINK_MESSAGE_INFO` and `MAVLINK_MESSAGE_NAMES`. 
So whichever dialect you import (e.g. common.xml) the `MAVLINK_THIS_XML_IDX==MAVLINK_PRIMARY_XML_IDX` and you pull in the info and names for the current dialect. However they don't get pulled in again, because the values ONLY match for the mavlink.h you pulled in first.
However this is fragile in that if you generate (say) ardupilotmega.xml and common.xml the libraries will be different, and depending on the order you can end up with two libraries with the same IDX value.  Consider building ardupilot …
=> Replace iterative IDX with hash of dialect name to remove build order dependencies

generator/gen_js.sh, generator/mavgen_javascript.py
- allow loading as both common.js (Node), and/or vanilla javascript in-browser
- include customised jspack and long  as part of node package.json - 'npm install' now works in generated output folder without further tweaks.
-  bump version no in generated output as its never happened before.
- fix package.json urls and keywords.
=> mavgen_javascript.py: small bugfixes

generator/mavschema.xsd
This enforces in the XSD/validator that every message must have at least one field.
@tridge @julianoes @auturgy Are you OK with this restriction? 
The cases I can think of where you might want to send an empty message are all commands - in almost every case you will want an ACK so you probably want to use a MAV_CMD. Also it is pragmatic.
This originates from #615, which demonstrates that mavgen_c generated code is broken if no field is specified. More generally, @peterbarker notes that:
- many of the generators might be broken
- empty messages may be a problem in some languages as zero-length objects can't have memory addresses.
=> XSD validation requires messages have at least one field

mavutil.py
Invalid argument gets spewed otherwise
Closes https://github.com/ArduPilot/ardupilot/issues/20251
@andyp1per
=> mavutil.py: mavtcp: recreate socket object in reconned for macosx

mavutil.py
@andyp1per 
previous fix for MacOSX killed reconnect on other platforms.
Should've done this in the first place... but it seemed to do no harm in initial testing.
=> mavutil: correct reconnect

generator/mavschema.xsd
Enums can also be work in progress. This enables them to be marked as such.
Further, this allows a "since" attribute to be added to the wip tag (but does not mandate it). The idea is that since allows you to easily see when the WIP tag was created, and thereby more easily assess whether the tag should be removed (or the whole element if implementation did not end up happening)
FYI @amilcarlucas - as per discussion in  https://github.com/mavlink/mavlink/issues/1732#issuecomment-960388791
=> XSD: WIP tags in enums

generator/C/include_v2.0/mavlink_helpers.h
This allows to disable signing to save some flash and stack usage if `MAVLINK_NO_SIGN_PACKET` is set.
=> Allow disabling signing for v2.0 C generator

DFReader.py
Logs now have messages called "MAV" in them, so you end up with a
keyerror if you look for MAV.percent in a condition.
Provide a very unlikely key for the log metadata
.... I wonder if we should choose a different magic key here?  This is DFReader which doesn't have anything to do with mavlink...
=> DFReader: provide __MAV__ message for log metadata

generator/mavschema.xsd
Name attributes must not contain whitespace - that's required because they are used as ids for generated items.
This adds XSD validation to ensure that only word characters are used in name attributes or the `_` character. 
Note that the pattern check of `"\w+"` should have been fine because my understanding is that in normal RE this includes the underscore. However running the validator failed on underscores so I was forced to explicitly support them: `"[\w_]+"`
@peterbarker This follows on from https://github.com/mavlink/mavlink/pull/1824.
Note: 
- leading and trailing whitespace would actually be OK, because you could reasonably strip this in the parser. This does not allow it though, and it is never "needed".
- I think the parser should also strip leading/trailing spaces.
- running …
=> XSD Validate - name attributes must not have whitespace

mavextra.py
useful for checking on radio margin
for example:
graph radio_margin(GPS,-35.2,148,4)
will graph the amount of altitude the aircraft could lose before losing line of sight to lat=-35.2 lon=148 with an antenna
at 4m above the ground
=> mavextra: added terrain helper functions

generator/mavgen_wlua.py
Previously, fields sometimes showed the wrong value, byte offsets were from the beginning of the IP packet, and truncated fields were omitted.
Now, the correct value is shown, byte offsets are from the beginning of the MAVLink packet, and truncated values are kept.
=> Fix Wireshark parsing logic

generator/java/lib/Messages/Description.java, generator/java/lib/Messages/Units.java, generator/java/lib/Messages/UnitsEnum.java, generator/mavgen_java.py, generator/mavgen_wlua.py
This is a pull request that just adds a Units and Description annotation to the MAVLink message classes for Java so that they can be retrieved at runtime for plotting and such similar to the C# class generator.
This one does not have a merge in the history and I'm closing this pull request:
https://github.com/ArduPilot/pymavlink/pull/636
=> Feature/add metadata to Java MAVLink message class fields 

tools/mavfft_isb.py
mavfft_isb is a pretty useful tool.  I like to use it as part of other tools.  I also wanted to integrate it into the MavExplorer partly to add the functionality of this tool into MavExplorer and to reduce duplication.  This PR will enable that.
Functionality should be unchanged so it can be used as it was for everyone that used it previously.
=> Make the mavfft_isb accessible to other programs

tools/mavlogdump.py
for reducing large logs for analysis
=> mavlogdump: added --reduce-rate msg

tools/mavlogdump.py
Before:
```
pbarker@fx:~/rc/logs$ time mavlogdump.py ./verloop/00000004.BIN -q 
real	0m34.787s
user	0m35.200s
sys	0m1.586s
pbarker@fx:~/rc/logs$ time mavlogdump.py ./verloop/00000004.BIN -q 
real	0m33.335s
user	0m33.683s
sys	0m1.664s
pbarker@fx:~/rc/logs$ 
pbarker@fx:~/rc/logs$ time mavlogdump.py ./verloop/00000004.BIN -q 
real	0m34.979s
user	0m35.332s
sys	0m1.642s
pbarker@fx:~/rc/logs$ 
```
After:
```
pbarker@fx:~/rc/logs$ time mavlogdump.py ./verloop/00000004.BIN -q 
real	0m32.996s
user	0m33.331s
sys	0m1.548s
pbarker@fx:~/rc/logs$ time mavlogdump.py ./verloop/00000004.BIN -q 
real	0m32.701s
user	0m33.073s
sys	0m1.639s
pbarker@fx:~/rc/logs$ 
```
So a few percent faster.
=> mavlogdump.py: create local for m.get_type()

generator/mavschema.xsd
For the TIMESYNC message we actually use nanoseconds, so to document that properly we need to add nanoseconds to the schema.
Related to https://github.com/mavlink/mavlink/pull/1878.
=> mavschema: add nanoseconds

mavextra.py
a `def sum` was added to this file relatively recently.  That overrides the built-in sum which was being called in this method, so average would always fail.  Import the old sum but rename it
=> mavextra.py: fix average(v, k, N) function

tools/mavlogdump.py
json doesn't permit non-utf-8, but our logs contain actual file contents in some fields.  This isn't going to work out well.
Past this the file content will not be recoverable; we could, perhaps, encode into base64 or similar instead of doing the conversion.
Closes #730
=> mavlogdump.py: don't die when handling bytestrings in dataflash logs

.gitignore, tools/magfit_WMM.py
Allows throttle based (on copter anyway), this means you can fit to throttle based and also remove a existing throttle based correction from flight data prior to calculating a current based one. Fit with `--Tmot`. You will almost certainly need to allow a larger CMOT limits when doing throttle based, at least a factor of 50 `--max-cmot 500`. 
Also allows to set a larger number of max iterations with `--iter 200` for example.
=> Tools: Magfit: throttle based

generator/mavschema.xsd
The units of Ampere hours (Ah) are required for the BATTERY_STATUS_V2 message defined in [RFC19](https://github.com/mavlink/rfcs/pull/19) and intended to merge in https://github.com/mavlink/mavlink/pull/1846
=> schema - Add Ampere-hours units

DFReader.py
These are arbitrary binary data and don't have a single-byte representation we can use in this text output if we want plain-ascii.
Only do this on py2 as py3 doesn't have a problem.
=> DFReader.py: correct fatal error when stringifying FILE messages

.github/workflows/mypy-generated.ini, .github/workflows/test.yml, generator/mavgen.py, generator/mavgen_python.py, mavutil.py, setup.py
This PR is based on #664  and contains 4 commits. It adds type annotation support in way that should not break mavlink for people stuck on Python2. Everyone else should benefit from the type annotations.
=> mavgen_python: Add python3 target with type annotations

generator/mavgen_python.py
This should fix the backward compatibility issue with the type annotation PR.
=> Use strings for char array mavlink fields again

DFReader.py, generator/mavcrc.py, mavutil.py, tools/mavlogdump.py
This improves the to_string method (in theory with correct typing it should not be necessary, but I don't want to reason about types before using only python3 with type annotations).
It also improves the type support of the crc computation and removes an instance where the crc computation was copy-pasted.
This PR should fix https://github.com/ArduPilot/pymavlink/issues/716.
=> Improve to_string and x25crc

generator/C/test/posix/Makefile
The node test in mavlink/mavlink CI fails because of:
```
standard/testsuite.h:29:13: error: ‘mavlink_test_standard’ defined but not used [-Werror=unused-function]
29 | static void mavlink_test_standard(uint8_t system_id, ...
|             ^~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
Ignoring the warning fixes CI.
See as an example:
https://github.com/mavlink/mavlink/actions/runs/3504071299/jobs/5869516184
FYI @davidbuzz, @hamishwillee, @auturgy
=> generator/C: fix node test in CI

.github/workflows/test.yml, generator/javascript/package-lock.json, generator/javascript/package.json, test_gen_js.sh
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> migrate CI node from 12 to 16 as 12 is deprecated

generator/mavgen_cpp11.py
Fix issue: https://github.com/ArduPilot/pymavlink/issues/762
Changes identical to [this fix](https://github.com/mavlink/mavlink-gbp-release/blob/master/patch/pymavlink/generator/mavgen_cpp11.py#L44-L47)
Related to PR: https://github.com/ArduPilot/pymavlink/pull/698
We prefer solution from this PR, but both works and both are OK.
=> fix EOF error for cpp11

mavutil.py
Hi, `mavutil.mavtcpin` may leave the `accept()`ed port open after closing, leading to `ResourceWarning`s like this one:
```
<frozen importlib._bootstrap>:241: ResourceWarning: unclosed <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 24550)>
Object allocated at (most recent call last):
...
File "/host/MY_MODULE", lineno 339
mavlink_msg = self._mavlink.recv_match(
File "/usr/local/lib/python3.10/site-packages/pymavlink/mavutil.py", lineno 502
m = self.recv_msg()
File "/usr/local/lib/python3.10/site-packages/pymavlink/mavutil.py", lineno 459
s = self.recv(n)
File "/usr/local/lib/python3.10/site-packages/pymavlink/mavutil.py", lineno 1317
(self.port, addr) = self.listen.accept()
File "/usr/local/lib/python3.10/socket.py", lineno …
```
=> Fix mavutil.mavtcpin not closing the accept()ed port on close()

mavutil.py
This will avoid MAVProxy considering a Herelink to be a vehicle.
Here's the pair of heartbeats from hereLink:
```
2023-01-19 11:23:23.88: HEARTBEAT (id=0) (link=None) (signed=False) (seq=139) (src=42/250)
type: 18 (MAV_TYPE_ONBOARD_CONTROLLER)
autopilot: 8 (MAV_AUTOPILOT_INVALID)
base_mode: 0
! MAV_MODE_FLAG_CUSTOM_MODE_ENABLED
! MAV_MODE_FLAG_TEST_ENABLED
! MAV_MODE_FLAG_AUTO_ENABLED
! MAV_MODE_FLAG_GUIDED_ENABLED
! MAV_MODE_FLAG_STABILIZE_ENABLED
! MAV_MODE_FLAG_HIL_ENABLED
! MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
! MAV_MODE_FLAG_SAFETY_ARMED
custom_mode: 0
system_status: 0 (MAV_STATE_UNINIT)
mavlink_version: 3
2023-01-19 11:23:24.38: HEARTBEAT (id=0) (link=None) (signed=False) (seq=107) (src=42/100)
type: 0 (MAV_TYPE_GENERIC)
autopilot: 8 (MAV_AUTOPILOT_INVALID)
base_mode: 0
! …
```
=> mavutil: do not consider MAV_AUTOPILOT_INVALID to be a vehicle heartbeat

generator/C/include_v2.0/mavlink_helpers.h, generator/C/include_v2.0/mavlink_types.h
this allows the caller to know why signing is being rejected, to provide better feedback to the user
=> generator-C: added last_status field for signing

generator/C/include_v2.0/mavlink_helpers.h
When MAVLINK_NO_SIGN_PACKET & MAVLINK_USE_CONVENIENCE_FUNCTIONS are defined, there is a build error
=> Fix for when signing disabled

generator/mavgen_cs.py
> I'm sorry my English sucks
When `description` in `param` is defined within `entry`  is multi-line, summary is malformed.
https://github.com/mavlink/mavlink/blob/b0a16eb7b09112d48bceb8a216fb3ad7693895e5/message_definitions/v1.0/development.xml#L169
It will look like this, there has been an error in the syntax.
```cs
///<summary> Fly a figure eight path as defined by the parameters.           Set parameters to NaN/INT32_MAX (as appropriate) to use system-default values.           The command is intended for fixed wing vehicles (and VTOL hybrids flying in fixed-wing mode), allowing POI tracking for gimbals that don't support infinite rotation.           This command only defines the flight path. Speed should be set independently (use e.g. MAV_CMD_DO_CHANGE_SPEED).           Yaw and other …
```
=> Fix the format of the output result of mavgen_cs.py

mavutil.py
Before, when reading high-latency messages that came from PX4, mavutil threw an exception because after the check for PX4, `msg.base_mode` was read immediately. It was not regarded that the `HIGH_LATENCY2` message does not contain a `base_mode` field.
This introduces a fix where the mode string for _all_ `HIGH_LATENCY2` messages is returned as `Mode(msg.custom_mode)`.
=> mavutil: Return mode as 'Mode(msg.custom_mode)' for high-latency streams

mavextra.py
=> mavextra: cope with more Lat/Lon/Lng combinations

generator/swift/Tests/MAVLinkTests/Testdata/common.xml
Fix typos in the message description. No functional change.
=> fix typos, cyles -> cycles, autonmous -> autonomous

DFReader.py, examples/add_msg_to_bin.py
useful for merging calculated data into a log
=> DFReader: added support for adding new messages to bin logs

generator/mavgen_lua.py
Need this for generating mavlink library for autotest.
=> generator: add support for relative path to lua mavlink module

generator/mavgen_wlua.py
This adds a new dissector port for 18570. This is the port that is exposed for PX4 running in WSL2.
I'm not sure if it more widely defined than that, or why it works and not the other ports.
=> WLUA - add new port for WSL 18570

generator/mavschema.xsd
I'm auto-adding documentation for MAV_CMDs that would be better if sent in COMMAND_INT rather than COMMAND_LONG, based on the `hasLocation` and `isDestination` properties (in https://github.com/mavlink/mavlink/pull/1992).
There are some MAV_CMDs (specifically in fence) that have position, but make no sense in a command. This adds the `missionOnly` attribute that can be applied to the very small subset of mission items to exclude them from getting that note.
Note that at this point haven't found a use case for `commandOnly` - most commands might in theory be used in missions, though for many it is a bit unlikely. I guess we might add this to indicate those commands that really only intended for commands but if desired would address in a separate PR.
=> XSD: MAV_CMD missionOnly attribute

generator/mavgen_lua.py
This gets the generated script through lua check so it could be committed to AP without re-work. https://github.com/ArduPilot/ardupilot/pull/24091
=> Generator: Lua: update to generate script that passes AP's luacheck

.github/workflows/test.yml
github has removed support for Py2
Minimal change to get CI passing
=> .github: remove 2.7 from workflows

mavutil.py
Fixed a problem in which mode mapping was not set correctly when starting SITL for quadplane due to this PR.
https://github.com/ArduPilot/ardupilot/pull/21596
=> mavutil.py: add vtol mode mapping

mavutil.py
Adds RTL mode to Blimp's mode mapping.
@peterbarker Do I need to do module update PRs for mavlink and ardupilot or will you guys do the updates?
=> mavutil: add RTL mode for Blimp

tools/mavfft_pid.py
=> mavfft_pid: allow PID target and error frequencies to be visualized

tools/extract_batch_imu.py
extract GYR and ACC log msgs from a log with ISB batch logging
=> tools: added extract_batch_imu.py

generator/C/include_v2.0/mavlink_helpers.h
This is fixing an issue within the C libs generated with mavgenerate.py for an ATMega4809 MCU. 
Using the ATMega4809 MCU compiled with AVR-GCC 5.4.0, during the decoding of the second byte of the msgid if it is non-zero, the high byte of the msgid would be set to 0xFF. This would in turn never get corrected in the receiving of the high byte of the msgid since it was ORd with the current msgid high byte (which should be 0, but is now 0xFF).
Adding this explicit typecast to the input byte of the second msgid byte seems to have fixed this issue and it works as expected on the ATMega4809 as well as a custom 64bit QGroundControl and 2 custom STM32 based boards.
I would also like to point out that without this fix, there were no issues in the decoding of the msgid on the custom 64bit QGC or on …
=> Fix bitshifting issue on 8bit AVR boards when using msgid > 255 with generated C libs

generator/C/include_v0.9/protocol.h, generator/C/include_v1.0/mavlink_helpers.h, generator/C/include_v1.0/protocol.h, generator/C/include_v2.0/protocol.h, generator/mavgen_c.py
this allows for sending messages with correctly incrementing sequence numbers without assuming channel 0 and without global status methods
This allows removal of a lot of code in ArduPilot that does save/restore of sequence numbers on channel 0, which also fixes race conditions
=> mavgen_c: added XXX_encode_status bindings

generator/mavgen_lua.py
This allows strings to be sent and received in AP with the generated parser. 
Tested with:
```
local mavlink_msgs = require("MAVLink/mavlink_msgs")
local STATUSTEXT_ID = mavlink_msgs.get_msgid("STATUSTEXT")
local msg_map = {}
msg_map[STATUSTEXT_ID] = "STATUSTEXT"
-- initialise mavlink rx with number of messages, and buffer depth
mavlink:init(1, 10)
-- register message id to receive
mavlink:register_rx_msgid(STATUSTEXT_ID)
function update()
local msg, chan = mavlink:receive_chan()
if (msg ~= nil) then
local parsed_msg = mavlink_msgs.decode(msg, msg_map)
if (parsed_msg ~= nil) and (parsed_msg.msgid == STATUSTEXT_ID) then
local ack = {}
ack.severity = 0
ack.text = "got msg: " .. parsed_msg.text
mavlink:send_chan(chan, mavlink_msgs.encode("STATUSTEXT", ack))
end
end
return update, 1000
end …
```
=> Generator: Lua: allow strings

.github/workflows/test.yml, generator/javascript/package-lock.json, generator/javascript/package.json
this fixes a node12 issue with optional chaining in Sinon lib. check [recent mavlink actions](https://github.com/ardupilot/mavlink/actions)
I'm adding the js tests here because it is weird that it only gets to fail on the other repo.
=> generators: js: fix sinon dependency to 15.2.0, add node tests

tools/mavplayback.py
I got this error using mavplayback.py.
```
Traceback (most recent call last):
File "/home/parallels/.local/bin/mavplayback.py", line 256, in <module>
app=App(filename)
File "/home/parallels/.local/bin/mavplayback.py", line 104, in __init__
self.next_message()
File "/home/parallels/.local/bin/mavplayback.py", line 199, in next_message
pos = float(self.mlog.f.tell()) / self.filesize
AttributeError: 'DFReader_binary' object has no attribute 'f'
```
=> tools: fix mavplayback.py

generator/mavschema.xsd
Fix typo in comments. Relates to https://github.com/mavlink/mavlink/issues/2062
=> mavschema - Typo 10E5 should be 1E5

tools/mavgen.py
=> tools: Add option to mavgen.py to return exit code if generation fails

generator/mavgen_wlua.py
The idea of this pull request is to add the field unit to the Wireshark display, whenever units are specified in the Mavlink dialect XML file. For example, output is as shown below, where the text such as "[us]", "[degE7]", etc is new:
```
Payload: GPS_RAW_INT (24)
time_usec (uint64_t) [us]: 3625540000
fix_type (GPS_FIX_TYPE): GPS_FIX_TYPE_3D_FIX (3)
lat (int32_t) [degE7]: 514783466
lon (int32_t) [degE7]: -25922214
alt (int32_t) [mm]: 56900
eph (uint16_t): 100
epv (uint16_t): 100
vel (uint16_t) [cm/s]: 0
cog (uint16_t) [cdeg]: 0
satellites_visible (uint8_t): 16
alt_ellipsoid (int32_t) [mm]: 0
h_acc (uint32_t) [mm]: 1000
v_acc (uint32_t) [mm]: 1000
vel_acc (uint32_t) [mm]: 200
hdg_acc (uint32_t) [degE5]: 0
yaw (uint16_t) [cdeg]: 0
``` 
Code lines changed is quite small, and I have done a …
=> Mavgen WLua: Add param units to display

mavutil.py
Found this one when adding a custom mavlink message.
The decoding of the packet affects the mav_loss calculation because the unknown message does not have its header populated. 
To a user, this could appear as though the vehicle radio link is intermittent/bad.
=> mavutil: Do not use unknown messages to calculate number of lost packets

generator/mavschema.xsd
For exactly the same reason that they are useful on parameters it would useful to have max, min, increment on fields - i.e. to restrict values as displayed in the UI and to make it easier to enforce ranges and test ranges in messages.
FYI @peterbarker @amilcarlucas , a high level view on the current schema is shown below prior to this PR. Are there any that we should have in both other than these? I don't think so, except possibly for decimalPlaces (not in any hurry to add it)
Another change we might make is to restrict some of these on `enum` - i.e. you shouldn't specify units if you have an enum and so on. I don't see it as a risk, but as a nice to have. OK?
---
MAV_CMD
- attributes
- value (an id number)
- name
- hasLocation | isDestination
- wip | deprecated | superseded (?)
- …
=> mavschema.xsd - max, min, increment on fields

mavutil.py
This PR proposes a few small updates to the outputting of values performed by the dump_message_verbose function in mavutil.py. (I've already started doing similar things for Wireshark, but am keeping that PR separate).
_- Basic unit conversions moved into lookup table, and degE5 added_
To make it a bit easier to read and add to, I replaced the if/elif/elif/... block with a lookup table, which should make it easy to add others in the future. The key is old unit, and the values are an array containing the divisor and new unit, e.g.:
```python
dump_message_unit_decoder = {
"d%":     [10.0,       "%"], ....
``` 
Whilst there I added a line for "degE5" (divisor:  100000, unit: deg).
_- Fields with "us" units shown with readable local time if value suggests it is a unix time_
If a field with a …
=> Mavutil: Output updates to dump_message_verbose

mavutil.py
two entries were renamed in the MAV_TYPE enumeration.  Since mavutil uses those enumeration entries without checking if they exist, using the entries which no longer exist goes poorly.
Rename was done here: https://github.com/mavlink/mavlink/pull/1818/files
Alternative to https://github.com/ArduPilot/pymavlink/pull/889
Tested on the command-line for the values currently in the mavlink commit references in ardupilot/master
=> mavutil: cope with enum entry rename

DFReader.py
the close function only closed the file, however to lift the lock on the file the mmap also needs to be closed.
I noticed that I was not able to move the file with shutil.move even after calling close on the DFReader object. After adding `self.data_map.close()` to the close function in DFReader the file was no longer locked after calling close.
Tested on Win11, python 3.12.0
=> fix close function in DFReader

mavextra.py
fix #635 
As pointed out in issue #635, there is an error in the distance_lat_lon function in mavextra, as `cos(lat1)` and `cos(lat2)` were being applied to the value in degrees not radians.
This PR fixes this, using the code proposed by @gitdillo, by ensuring all function inputs are converted before use.
I chose not to use the code from the gps_distance function in mp_util.py (as linked @khancyr), as the mp_util function calculates the rhumb line distance, rather than the great-circle distance, and I did not want to alter the original author's intent of the function.
I also added extra words to the comments of all 3 similar functions in mavextra.py and the radius_of_earth variable, to make it more clear which formula and earth radius are being used.
I checked a few spot points before and …
=> mavextra: correct radian conversion in distance_lat_lon function

DFReader.py
When reading a DF text log, the 'counts' and 'offsets' dictionaries end up being indexed by the message name as 'bytes', whereas the 'formats' and 'name_to_id' are indexed by message name as 'str'.
This PR aims to fix this to align the indexing to strings.
Effectively, there were 3 issues:
* `mtype = self.data_map[ofs:ofs+4]` gives bytes, which is then used as index without converting.
* `if mtype[3] == b',':` doesn't do as intended, as it always returns false in Python 3 (try: `b'abc,'[3] == b','`).
* Even if it did work, mtype[3] doesn't take account of messages 'EV' and 'PM' as they are only 2 chars long.
The fix uses decode and split to get the text up to the first comma (if there is one) as str, which should then align.
Note that I came across this after seeing that the MAVExplorer …
=> DFReader_text: some meta-data dicts are indexed by bytes instead of str

DFReader.py, tools/mavlogdump.py
The main aim of this PR is to make the DF log reader 'unit aware', by reading the UNIT and MULT messages from the log, and then storing the resulting units as part of the format definition.
In order to test it, the update also adds a dump_verbose method which is used by mavlogdump (and later MAVExplorer dump command, with separate PR) when the --verbose argument is used.
(Previously verbose outputs were only available with Mavlink/TLog files)
Note that the multipliers specified in the MULT/FMTU messages do not alter data values (so nothing should be unexpectedly different to any users or other tools), but rather amend the unit with a suitable prefix. e.g.: Ah * 1e-3 => mAh.
This is in line with the logic used to populate the wiki.
Cache units and multipliers in unit_lookup and mult_lookup …
=> DFReader: Read unit data from log and add dump_verbose function to DFMessage

tools/mavlogdump.py
The PR is to fix #905.
It removes the logic which cuts out subsequent messages from CSV output if they have the same timestamp.
This typically affects messages with instances like IMU, where only the last one of a sequence would be output.
It would also affect messages like MSG, MULT, UNIT, etc, which may be added to the log file in batch.
I have tried a few files, with a few message types, and can now see expected output. For example, the IMU data for both instances even when they have the same timestamp:
```
$ mavlogdump.py --format=csv --types=IMU ArduPlane-Soaring-00000045.BIN
timestamp,TimeUS,I,GyrX,GyrY,GyrZ,AccX,AccY,AccZ,EG,EA,T,GH,AH,GHz,AHz
1704628006.74000502,1745135,1,-0.00015193763829302043,9.939412120729685e-05,-3.919340451830067e-05,-0.0009788739262148738,-0.0027941113803535 …
```
=> mavlogdump: CSV option: Don't cut out messages with same timestamp

tools/mavplayback.py
Currently, rewind & forward buttons as well as dragging across the timeline don't work and produce an error:
`Exception in Tkinter callback
Traceback (most recent call last):
File "/usr/lib64/python3.11/tkinter/__init__.py", line 1948, in __call__
return self.func(*args)
^^^^^^^^^^^^^^^^
File "/home/szymon/development/opensource/forks/pymavlink/tools/mavplayback.py", line 136, in forward
self.mlog.filehandle.seek(pos)
^^^^^^^^^^^^^^^^^^^^
AttributeError: 'mavmmaplog' object has no attribute 'filehandle'`
Some of the calls were changed from mlog.filehandle to mlog.f by @tridge in #890, it seems to me that the remaining have to be changed as well.
=> Tools: fix mlog attribute in mavplayback

generator/mavschema.xsd
Within the Mavlink schema, enum values are currently limited to 10 decimal, 8 hex, or 32 binary digits.
However, we already have two fields which are bitmasks and use uint64_t type (AUTOPILOT_VERSION.capabilities and GENERATOR_STATUS.status). This character limit means that you can't currently specify a value using (most of) the higher 32-bits.
I came across this while trying to build a test case for #895.
My proposal is to extend the character limit to 20 decimal, 16 hex or 64 binary digits to allow for this.
@hamishwillee - does this make sense?
I did wonder if it might be useful to be allowed to specify values as powers of 2 (e.g. "2^0", "2^4", "2^55") to be more readable as the numbers get bigger, but as this would require work on the generators, so have not proposed it.
I also …
=> MavSchema: Allow 64-bit enum values to be specified

requirements.txt
As of approx 06/02/2024, the pytest part of pymavlink CI began failing on Python v3.8+. This appears to be because pytest 8.0.0 is now being used as opposed to 7.4.4 before.
For now, this PR offers a fix, by pegging the version at <=7.4.4 in requirements.txt.
(Note that we need to use "<=" as Python 3.5 is using an older version of pytest).
For info, the error message when using pytest 8.0.0 was:
```
_____________________ ERROR collecting tests/test_trim.py ______________________
ImportError while importing test module '/home/runner/work/pymavlink/pymavlink/tests/test_trim.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/importlib/__init__.py:127: in import_module
return …
```
=> CI: Use pytest<=7.4.4 as 8.0.0 will not run the tests

generator/mavschema.xsd
This is a follow-up from comments in #915.
It allows use of powers of 2 to specify enum values - which would be most useful for big bitmasks.
Example syntax is: `<entry value="2**7" name="BIT7" />`
@hamishwillee in https://github.com/ArduPilot/pymavlink/pull/915#issuecomment-1932957229 wrote:
> FWIW More than happy for you to try it but:
> 
> * consider restricting to bitmasks
I couldn't see how this was possible, as this is part of the rule for the 'value' field of enum 'entry' tag. Although I suspect xsd syntax can do many things that I don't know about!
> * allow either format
The syntax allows the user to use any of: decimal, hex, binary, power of 2.
> * we will need to have a period where other generators have a chance to catch up before we modify the XML.
No XML has been changed. …
=> Mavschema: Allow enum values to be powers of 2

generator/javascript/test/message10.js, generator/javascript/test/message20.js, generator/mavgen_javascript.py
This PR updates the Javascript generator to automate the filling of the HEARTBEAT.mavlink_version parameter.
As per the C Mavgen, it uses 'omit_arg' parameter of the field to determine that the parameter should be omitted from the input parameter list, and 'const_value' parameter to determine the value to set.
When building a HEARTBEAT message via the constructor the parameter should no longer be specified, and the test cases have been updated to do this.
When the message is being read from a data stream, the value is correctly populated to whatever its actual value is, as this uses direct field assignment and not the constructor to build the message (I have tested this).
The change in output ends up looking like this:
from:
```javascript
/*              ...
system_status             : …
```
=> Mavgen JS: Heartbeat message mavlink_version should be automaticlly completed

tools/mavlogdump.py
I was trying to use mavlogdump to generate a .mat file from a .bin file, and forgot to specify the --mat_file argument. I found the exception thrown by the call to scipy.io.savemat was not very clear as to my mistake.
This PR adds a check before processing the input file that the required argument is specified, and gives the user a clearer message as follows:
`mat_file argument must be specified when mat format is selected`
=> mavlogdump: show clear error message when mat_file arg is missing

tools/mavlogdump.py
As @peterbarker pointed out in comments on #928, quit() should not be normally be used in scripts, but instead sys.exit() is preferred.
This PR replaces the uses of quit() and exit() in mavlogdump with sys.exit(1) - all uses are error conditions, hence using return code 1.
I tested a few of the error conditions out, and checked they return neatly with the correct error code set, for example:
```
$ mavlogdump.py --format=csv file.BIN 
Need exactly one type when dumping CSV from bin file
$ echo $?
1
```
=> mavlogdump: Use sys.exit instead of quit on error

generator/mavgen_javascript.py
I am using the Mavlink JS Nextgen output in a React Native project on Android mobile device.
In Node JS, the 'Buffer' object is globally available by default, but in React Native this is not the case.
This PR adds the line: `var Buffer = require('buffer').Buffer;` to the generated output.
This provides the Buffer object in React Native, and it is benign to also include this line in Node JS.
I have successfully used the updated generator in my React Native project, and checked that it also can be imported successfully in Node. Also, the CI tests the generator output in various versions of Node.
=> Mavgen JS: Add require('buffer') statement to allow JS output to work in React Native

mavutil.py
Users of this library may want to handle these values being wrong. While it is possible to handle sys.exit, it is more conventional to raise a ValueError on incorrect data passed as an argument.
=> mavutil: Raise ValueError instead of exiting

DFReader.py
This PR adds a DFMetaData class to the DFReader.m file, which is used to handle LogMessage XML meta-data for use by MAVExplorer and potentially other tools. It links to PR https://github.com/ArduPilot/MAVProxy/pull/1337.
The class is set as the metadata attribute of DFReader class, and at present includes methods:
* reset - clear cached data, in case of new download, or change of vehicle type
* dot_mavproxy - copy of function in mp_util, to avoid dependency on MavProxy
* metadata_tree - return metadata map for use by other function, including cached version once loaded.
* print_help - print the help for specified log message
* get_description - return the description of the specified log message
Tested using the "logmessage help" command in MAVExplorer (with PR …
=> DFReader: Create DFMetaData class to handle logger metadata

generator/mavgen.py
Closes https://github.com/ArduPilot/pymavlink/issues/596
=> generator/mavgen.py: honour MDEF from environment in dynamic generation

tools/mavfixtimedrift.py
this fixes TimeUS in logs for clock drift from bad crystals on some flight controllers
by default it just calculates and reports the drift, with --fix it creates a new log with TimeUS fixed
example:
and with --fix:
=> tools: added mavfixtimedrift.py

DFReader.py
.. taking the conservative approach to this new feature failing....
@shancock884
=> DFReader.py: add bitmask data to verbose print output

generator/mavgen_javascript.py, generator/mavgen_javascript_stable.py
Currently, the javascript code will throw a wrong CRC error even though the crc is correct with a probability of 1 to 65535.
This happens because in the x25Crc method we don't differentiate `crcIN === undefined` from `crcIN === 0`.
=> Javascript: Fix wrong crc calculation

.github/workflows/test.yml, generator/C/test/posix/Makefile, generator/C/test/posix/parse_tlog.c, generator/mavcrc.py, requirements.txt
fastcrc runs about 3x faster than existing x25 crc
=> use fastcrc if available

generator/mavgen_wlua.py
This PR is to fix https://github.com/mavlink/mavlink/issues/1862, fix https://github.com/mavlink/mavlink/issues/2073 and fix #701. (In particular https://github.com/mavlink/mavlink/issues/2073 includes the discussion about how it was figured out!).
There is a bug in wireshark, whereby a double is cast to an unsigned int when it should be a signed int, before being used as a signed int. On Linux this works, but on Mac negative values get cut to zero ([here is why](https://embeddeduse.com/2013/08/25/casting-a-negative-float-to-an-unsigned-int/)).
Thanks to @rotu, a Wireshark fix has been merged in [wireshark/wireshark#15438](https://gitlab.com/wireshark/wireshark/-/merge_requests/15438).
This PR provides a workaround/fix to avoid the issue completely, so that it will work even with older …
=> Mavgen WLUA: Fix incorrect display of negative ints on mac

generator/mavschema.xsd
This falls out of the discussion in https://github.com/mavlink/mavlink/issues/2062#top
[GPS_RAW_INT.eph](https://mavlink.io/en/messages/common.html#GPS_RAW_INT) and `.evp` and same property names in [HIL_GPS](https://mavlink.io/en/messages/common.html#HIL_GPS) are unitless values, so correctly don't have units added.
However they are scaled by 100 and there is no way to know that programmatically. IN order to allow programmatic comparisons and conversions it is useful to supply this information.
This creates a unit `1E2` that indicates a unitless value scaled by 100. 
FYI @shancock884
=> mavschema - 1E2 for scaled unitless values

generator/mavschema.xsd
Relates to https://github.com/mavlink/mavlink/issues/2062, point 2.
> 2/ Satellite Azimuth unit doesn't consider scale factor
The satellite_azimuth field of the GPS_STATUS message has a unit of "deg", but the description says "0: 0 deg, 255: 360 deg".
To be consistent with other units, and allow automatic value decoding, I would propose that a specific unit is used here too.
e.g. "degS8" (meaning "Degree Scaled to 8 bit integer"), or "deg/360*255" or any sensible simplification thereof.
I would also question if 255 is really supposed to be 360deg - as this means a value of 0 and 255 represents the same angle.
Perhaps what was intended is that 255 represents 360-(360/256) = 358.59375 ?
This PR adds the "degS8" unit, and an associated comment to the mavschema.xsd file.
=> Add multiplier value for GPS_STATUS.satellite_azimuth where 255 means 360deg

DFReader.py
Following #937, I noticed a few things with bitmask displays that wasn't quite behaving, which this PR aims to fix:
1/ The bits of ArmChecks are not being displayed when doing `dump --verbose ARM`
This was because these bits have no description, and the `except KeyError` does not catch this.
Fixed by using if `hasattr(bit, 'description')` instead.
2/ The last bit was always missing (e.g. CHANGED bit on POWR.Flags)
This was because `for i in range(bit_offset)` needs a `+1`.
Actually I realised this should rather be using `highest_bit+1` in case more bits are set than defined.
3/ If any bit is missing a definition from the XML, then this and subsequent bit are not shown 
This was because `bang` variable was being used undefined in this case.
Fixed by defining `bang` earlier, so it is …
=> DFReader: Fix some missing bitmask info in dump verbose

generator/mavgen_wlua.py
I came across an error using  the Wireshark dissector on Windows, with messages containing unix time in μs.
```
Lua Error: ...Data\Roaming\Wireshark\plugins\mavlink_ardupilotmega.lua:22: bad argument #1 to 'date' (invalid conversion specifier '%Z')
[Expert Info (Error/Undecoded): Lua Error: ...Data\Roaming\Wireshark\plugins\mavlink_ardupilotmega.lua:22: bad argument #1 to 'date' (invalid conversion specifier '%Z')]
[Lua Error: ...Data\Roaming\Wireshark\plugins\mavlink_ardupilotmega.lua:22: bad argument #1 to 'date' (invalid conversion specifier '%Z')]
[Severity level: Error]
[Group: Undecoded]
```
The %Z date formatter should give the timezone as a short name, but it is not working on Lua 5.2.4 on Windows - as currently used in Wireshark. It worked on Linux, and is already fixed in Lua …
=> WLua: Handle LUA error with %Z date format on Windows

DFReader.py
@shancock884 
```
Rsn: 2 GCS_COMMAND 
2024-06-30 03:16:09.587: MODE
TimeUS: 4987197968 µs
Mode: 6 
ModeNum: 6 
Rsn: 2 GCS_COMMAND 
```
(we don't emit the mode enumerations into the ArduPilot metadata yet)
```
dump --verbose ARM 
MAV> 2024-06-30 03:17:41.162: ARM
TimeUS: 5078772628 µs
ArmState: 0 
ArmChecks: 0 
! ARMING_CHECK_ALL
! ARMING_CHECK_BARO
! ARMING_CHECK_COMPASS
! ARMING_CHECK_GPS
! ARMING_CHECK_INS
! ARMING_CHECK_PARAMETERS
! ARMING_CHECK_RC
! ARMING_CHECK_VOLTAGE
! ARMING_CHECK_BATTERY
! ARMING_CHECK_AIRSPEED
! ARMING_CHECK_LOGGING
! ARMING_CHECK_SWITCH
! ARMING_CHECK_GPS_CONFIG
! ARMING_CHECK_SYSTEM
! ARMING_CHECK_MISSION
! ARMING_CHECK_RANGEFINDER
! ARMING_CHECK_CAMERA
! ARMING_CHECK_AUX_AUTH
! ARMING_CHECK_VISION
! ARMING_CHECK_FFT
! ARMING_CHECK_OSD
Forced: 0 
Method: 13 …
```
=>  DFReader.py: emit enumeration value name when verbose-dumping 

mavutil.py
On a link with multiple mavlink device, we store the state of all device into the sysid holding the port which is tottally wrong.
The easiest way to see this bug in action is to run two SITL instance connect via mavlink. Then on either mavproxy instance, use "alllinks mode guided" the SITL instance directly connect to mavproxy will update its mode fine, the other will change to another mode 
GDB screen from mavproxy on the call of mavutil post_message() function
After fix :
=> Mavutil: fix wrong sysid_state update from sysid mismatch

tools/mavgen.py
I'm thankful that @nexton-winjeel added the option to have the exit code indicate an error in https://github.com/ArduPilot/pymavlink/pull/863. I'm asking myself why this isn't default. I imagine the generator to be called automatically by CI or like in my case a build step in PX4. Shouldn't it fail by default instead of silently succeeding without a certain dialect properly generated? I would have expected that.
I changed it for PX4 to explicitly add the flag in https://github.com/PX4/PX4-Autopilot/pull/23313 but want to save the next developer having the hassle.
**EDIT:** To clarify some mistakes e.g. using a non-existing type in a message definition makes the generation throw an exception and fail early. Other mistakes like referring to a non-existing enum don't throw an exception but …
=> mavgen: always report generator errors in the exit code

mavutil.py, requirements.txt
This adds support for a WebSocket server connection type. This is used with the prefix `wsserver`. For example `wsserver:localhost:5763`.
https://github.com/mavlink/mavlink2rest also does WebSockets, however, it sends a MAVLink JSON object in a text WebSocket message. This sends raw MAVLink in the binary WebSocket message. 
I have tested with a browser based client. It does work, but I wrote it too, so its not a independent test. I have also only tested sending from server to client, not from client to server. 
The more common python WebSocket [library ](https://websockets.readthedocs.io/en/stable/) is designed for a asyncio workflow which makes it hard to integrate here. I ended up using [wsproto](https://python-hyper.org/projects/wsproto/en/stable/) mostly because it had a synchronous …
=> mavutil: add WebSocket Server mavlink_connection type

mavutil.py
this allows a user to use pymavlink without these libraries installed so long as they don't try tyo use websockets
=> mavutil: import websocket libs in init function

mavutil.py
=> mavutil: correct processing of zero-length logs

examples/mavftp_example.py, mavftp.py, tests/test_mavftp.py
Like spoken on the dev call this adds a mavftp library and an example script that uses it to:
This is the `--help` of the main mavftp.py application, it supports a similar syntax to the MAVProxy embedded mavftp functionality:
```
usage: mavftp.py [-h] [--baudrate BAUDRATE] [--device DEVICE] [--source-system SOURCE_SYSTEM] [--loglevel LOGLEVEL] [--debug DEBUG] [--pkt_loss_tx PKT_LOSS_TX]
[--pkt_loss_rx PKT_LOSS_RX] [--max_backlog MAX_BACKLOG] [--burst_read_size BURST_READ_SIZE] [--write_size WRITE_SIZE] [--write_qsize WRITE_QSIZE]
[--retry_time RETRY_TIME]
{get,getparams,put,list,mkdir,rmdir,rm,rename,crc} ...
MAVFTP - MAVLink File Transfer Protocol. A tool to do file operations between a ground control station and a drone using the MAVLink protocol.
positional arguments: …
```
=> Add mavftp library and example code that uses it

mavutil.py
For reasons I don't really understand the import inside the class init works on Python 3.8.3 where I originally tested but not on Python 3.12.3. ~~This moves the import out of the init which works for both versions.~~ I now have the import in each function of the class that needs it, seems odd, but it does work.
=> mavutil: WebSockets: fix wsproto import for newer python versions

mavwp.py
```
/home/pbarker/.local/lib/python3.12/site-packages/pymavlink-2.4.41-py3.12.egg/pymavlink/mavwp.py:505: SyntaxWarning: invalid escape sequence '\s'
not re.match("[-0-9.]+\s+[-0-9.]+", version_line)):
```
=> mavwp: mark re.match pattern as regex string

.github/workflows/pylint.yml, .pylintrc, mavftp.py, mavftp_op.py, mavftpfs.py, tests/test_mavftp.py
This mounts mavftp as a virtual filesystem, which allows for more "human" interfacing with it.
There are caveats. It is obviously slower than doing things on your own machine. but this does allow interfacing using any filebrowser, for instance.
So far the filesystem is mounted as read-only. as there's no mavftp interface to write to a sector of a file, we'd have to create an abstraction layer that caches the whole file...
[Screencast from 2024-09-17 12-21-47.webm](https://github.com/user-attachments/assets/60fcbc26-295a-419a-87e4-89f83f856005)
=> Update MavFTP code, add MavFTPfs example/tool

.github/workflows/pylint.yml
Fix the commit that got merged without passing CI
=> .github: Use / as a file path separator

mavextra.py
similar to what other function in here to, don't poison the lowpass result with nans - just ignore the bad value
=> mavextra.py: return None if nan passed as new value to lowpass

examples/combine_logs.py
=> added a tool that combines 2 logs into one

tools/mavtogpx.py
values plotted are a mix if you specify something like POS
=> mavtogpx.py: allow specification of which message to actually plot

generator/mavgen_lua.py
This adds checking of the checksum on message decode. This allows AP to pass unknown messages which have not passed its checksum.
=> Generator: Lua: add support for checksum on decode

mavwp.py
we supported the incusion of fences within waypoints for a short period of time in a branch of ArduPilot.  This was removed, but we still have cestiges like this
=> mavwp: remove old fences-in-waypoints code

generator/C/include_v2.0/mavlink_helpers.h
I have been wondering for a while why I sometimes see MAVLink components "appear" with random sysid/compid when I leave a system running for some time.
Today I finally caught the bytes of such a case, the offending bytes were:
`{253, 0, 1, 0, 0, 3, 1, 1, 42, 0, 185, 186, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};`
This is msgid 10753 from sysid 3, compid 1 with payload len 0. It's presumably signed, hence the trailing zeros.
It turns out the msgid is way out of the CRC_EXTRA table and hence the mavlink_get_msg_entry(msgid) function returns NULL. In that case 0 is ignored and we carry on parsing.
My suggestion is to reset parsing when we don't know the CRC_EXTRA of the message to avoid flagging noise as a valid message.
=> generator/C: Don't parse messages outside CRC_EXTRA

DFReader.py
The aim of this PR is to add the hex value alongside the decimal value, when displaying bitmask fields with the "dump --verbose" command in MavExplorer, as I think it is easier to follow which bits are set in hex.
This is also more in-line with how bitmasks are shown from TLog files when using "dump --verbose".
For example, on XKF4:
```
> dump --verbose XKF4
2024-12-04 14:53:37.722: XKF4
...
SS: 107327 (0x1a33f)
ATTITUDE (attitude estimate valid)
HORIZ_VEL (horizontal velocity estimate valid)
VERT_VEL (vertical velocity estimate valid)
...
```
Tested locally with a variety of messages containing bitmasks.
=> DFReader: In dump verbose show hex value for bitmask fields

tools/mavfft_pid.py
Fast rate code is now merged. This is required to read the correct sample rate.
=> mavfft_pid.py: handle logs using fast rate control

generator/mavgen_wlua.py
After updating Wireshark to v4.4.2 (Windows), I noticed that the SYSTEM_TIME message was showing an LUA error:
```
Lua Error: ardupilotmega.lua:21: bad argument #2 to 'date' (number has no integer representation)
```
The issue appears to be that the os.date function no longer accepts a floating point input. This is fixed by applying math.floor to the 'seconds' part of the timestamp before calling os.date. The microseconds part was already being appended to the output string separately.
As a side-note, this also avoids potentially calculating "value:tonumber() / 1000000.0" three times.
Output tested, and now working like so:
```
MAVLink Protocol (22)
Payload: SYSTEM_TIME (2)
time_unix_usec (uint64_t) [us]: 1733755765960647 (2024-12-09 14:49:25.960647 GMT Standard Time)
time_boot_ms …
```
=> Mavgen WLua: Pass unix time as integer to os.date

generator/mavgen_python.py
Because enums are represented as lists with no class it would be a big change to add the bitmask property to the enum. Instead this sets the existing display property on the field which uses the enum to "bitmask" if no value is directly provided and the enum is marked as a bitmask in the xml.
https://github.com/mavlink/mavlink/pull/2215
https://github.com/ArduPilot/mavlink/pull/383
As far as I can tell the other generators deal with this correctly already.
=> Generator: python: set display bitmask based on enum if no value is provided directly

generator/mavgen_c.py
Most of the code was already compatible with python3 except for the small change for iteritems. The builtins and print_function were put in to make it python3 compatible, so those are no longer necessary.
=> Update mavgen_c to python3

.github/workflows/test.yml
This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101
=> .github: move workflows onto 22.04

.github/workflows/pylint.yml, .github/workflows/test.yml, files/archlinux/PKGBUILD, generator/mavcrc.py, generator/mavgen.py, generator/mavgen_python.py, mavutil.py, setup.py, test_generate_all.sh, tools/mavftpdecode.py, tools/mavgraph.py, tools/mavlogdump.py, tools/mavtomfile.py
This removes support for generating Python2 bindings, and for running the generator under Python2.
Working with the non-inline type annotations was rather painful when modifying them recently.  It was a good hack, but we really shouldn't need it any more given how dead Python2 is now.
=> Remove Python2 support; inline typing markup into templates

.github/workflows/test.yml
```
Traceback (most recent call last):
File "/home/runner/work/pymavlink/pymavlink/setup.py", line 90, in <module>
setup (name = 'pymavlink',
File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/setuptools/__init__.py", line 117, in setup
return distutils.core.setup(**attrs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 186, in setup
return run_commands(dist)
^^^^^^^^^^^^^^^^^^
File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 202, in run_commands
dist.run_commands()
File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 1002, in run_commands …
```
=> .github: use pip to install pymavlink

DFReader.py, dfindexer/dfindexer.c, dfindexer/dfindexer.h, dfindexer/dfindexer_cy.pyx
Adds the progress-bar back for MAVExplorer. It fires every 4 million messages or so. For a 4GB log, that's about one every 4% through the log. For smaller logs, it takes bigger % jumps, but they go fast.
=> dfindexer: add progress callback

DFReader.py
Forgot to make sure that the param dict initialized the same as before. This regression was due to the changes I made to recv_match to make it faster when you truly only care about one type (the so-called "strict" option that I introduced).
I've added back the original side-effects of param initialization to both init_clock and flightmodes_list.
I thought about building up the initial params explicitly by just doing a recv_match through all the 'PARM' messages, which would build a dict of the param values at the end of the log, which isn't the old behavior (the old behavior is "param values at the time of first GPS fix", or, if you call flightmodes_list, it's "param values at the end").
Similarly I don't think it's right to build up the first values seen for each param, since sometimes …
=> DFReader Param Init

.github/workflows/python-publish.yml
Alternative to https://github.com/ArduPilot/pymavlink/pull/1038
- Builds wheels for all linux systems (and python versions 3.8+)
- xml packages needed to be installed on Alpine (for musllinux i686)
- We should build Mac and Windows wheels in a future PR so they can benefit from the speedup
- Double-check the existence of the wheels and copy them to the `dist` folder
- Build the sdist so pip can fall back to compiling it
- Upload artifacts so they can be checked and tested (I have not actually tested installing the wheels or the sdist, but I see no reason why they shouldn't work)
=> CI: ensure we build properly tagged wheels

mavutil.py
In the function auto_mavlink_version, the save of the mav.callback was here, but not the one related to the mav.send_callback, so I added it.
=> Saving send_callback after the use of auto_mavlink_version

DFReader.py
I broke the human-readable .log loading. My opimizations were mainly targeted at .bin, and I forgot to test to make sure I didn't cause a regression to .log. These aren't used much, so this probably doesn't need an emergency release.
1. My new optimizations to init_clock rely on being called _after_ init_arrays.
2. The type set in skip_to_type is handled subtly differently in DFReader_text, and I didn't pay close enough attention when copying the "strict" handling over.
=> DFReader_text: fix loading bugs

generator/mavschema.xsd
This is needed to fix a embarrassing issue with the AIS message, see: https://github.com/mavlink/mavlink/pull/2281
=> generator: schema: add decidegrees per second units

DFReader.py
Some logs, like ones created by other tools (not autopilots), frequently don't have some of the metadata messages like UNIT. Don't crash when that happens.
The only message we need to assume exists is FMT
=> DFReader: init_arrays_fast: fix key error

.github/workflows/python-publish.yml, pyproject.toml
This PR contains two fixes:
This is necessary to fix a [recent build failure](https://github.com/ArduPilot/pymavlink/actions/runs/16010298504). lxml just released a new version 6.0.0, which does not have a wheel for cp38-manylinux_aarch64, where the previous version did. The thing is, there's really no reason for us to need to pip install lxml into the isolated build environment; it's a runtime dependency only. `pyproject.toml` does not need this in there.
This also lets me build the windows-arm wheels now (surely few, if any, care about that yet).
I'm pretty sure it doesn't need "future" in there either, but I didn't bother removing that as it isn't hurting anything like the lxml thing is.
Split out from #1072
I went through the [change …
=> cibuildwheel updates

mavftp.py, mavutil.py, tests/snapshottests/test_wlua.py, tools/mavfft_isb.py, tools/mavftpdecode.py, tools/python_array_test_recv.py, tools/python_array_test_send.py
% `ruff check --select=UP009,UP018,UP021,UP039 --output-format=concise`
```
mavftp.py:1241:21: UP018 [*] Unnecessary `bytes` call (rewrite as a literal)
mavutil.py:940:17: UP039 [*] Unnecessary parentheses after class definition
tests/snapshottests/test_wlua.py:91:9: UP021 [*] `universal_newlines` is deprecated, use `text`
tools/mavfft_isb.py:75:18: UP039 [*] Unnecessary parentheses after class definition
tools/mavftpdecode.py:33:16: UP018 [*] Unnecessary `bytes` call (rewrite as a literal)
tools/mavftpdecode.py:64:17: UP018 [*] Unnecessary `bytes` call (rewrite as a literal)
tools/python_array_test_recv.py:2:1: UP009 [*] UTF-8 encoding declaration is unnecessary
tools/python_array_test_send.py:2:1: UP009 [*] UTF-8 encoding declaration is unnecessary
Found 8 errors.
[*] 8 fixable with the …
```
=> Remove miscellaneous Python 2 anachronisms

.github/workflows/pylint.yml, .pylintrc
https://pypi.org/project/pylint
Increased `max-positional-arguments` from the default of 5 to 9.
https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/too-many-positional-arguments.html
```
uvx --with=requests --with=setuptools pylint==3.3.7 __init__.py dialects/__init__.py \
dialects/v09/__init__.py dialects/v10/__init__.py dialects/v20/__init__.py \
examples/__init__.py generator/__init__.py tests/test_mavxml.py tools/__init__.py \
mavftp.py mavftp_op.py examples/mavftp_example.py examples/status_msg.py \
tests/test_mavftp.py tests/test_mavxml.py
```
=> .github: Upgrade to pylint v3.3.7

.github/workflows/test.yml
Tests should tell us if things are broken on the latest stable versions of Node.js or Python before users do.
* https://github.com/actions/setup-node#supported-version-syntax
* https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-the-python-version-input
> [x-ranges](https://github.com/npm/node-semver#x-ranges-12x-1x-12-) to specify the latest stable version of Python (for the specified major version):
Also, do not fail silently if `requirements.txt` is deleted.
=> .github: Test on the latest Long Term Support versions of Node.js and Python

generator/mavgen_python.py
This PR updates the robust parsing mode of the Python MAVLink parser such that when it encounters garbage between the end of the previous message and the next MAVLink magic byte, it returns a single `MAVLink_bad_data` instance containing the entire garbage section instead of returning it byte-by-byte. This improves the performance of the parser significantly when the stream being parsed contains either a mixture of MAVLink and non-MAVLink messages, or when it contains lots of garbage data. A possible example is MAVLink-over-UDP when the underlying serial-to-UDP module is not aware of MAVLink's internal structure and may break MAVLink packets into multiple UDP packets. The loss of a UDP packet may then leave MAVLink packet fragments in the stream being parsed.
In a captured stream of …
=> Robust parsing returns BAD_DATA up to the next magic byte

tests/snapshottests/__snapshots__/test_wlua.ambr, tests/snapshottests/test_wlua.py
Currently the Wireshark LUA test cases truncate all lines at 72 characters because the tshark output for byte-stream lines gets truncated with a '...' at one point.
This change alters the logic so that _only_ byte-stream lines are truncated, rather than _all_ lines.
Byte-steam lines are recognised by matching a regular expression of at least 60-consecutive [0-9a-z] characters.
This ensures that relevant parts of the test output are not lost. For example:
```
.... .... .... .... ...1 = MAV_PROTOCOL_CAPABILITY_MISSION_F
vs
.... .... .... .... ...1 = MAV_PROTOCOL_CAPABILITY_MISSION_FLOAT: True
```
This becomes even more relevant for a test case I plan to add for 64-bit bitfields in an upcoming PR fix for issue #895.
Tested via local running of pytest and CI.
=> WLua: Only truncate hex dump lines for test case output checks

generator/mavgen.py, tools/mavgen.py
The arg 'error_limit' of [mavgen.py](https://github.com/ArduPilot/pymavlink/blob/master/generator/mavgen.py) is not used anymore. So it could be deleted.
=> delete unused arg error_limit of mavgen.py

mavextra.py
When I use "map XKF1" inside MAVExplorer it seems to be using ORGN[1] instead of ORGN[0]
=> tools/mavextra.py: use the correct origin

generator/mavgen_objc.py
Part of https://github.com/mavlink/mavlink/pull/2317 initiative.
=> mavgen_objc.py: rename BOOL to MAV_BOOL

generator/javascript/test/mavlink10.js, generator/javascript/test/mavlink20.js, generator/mavgen_javascript.py, mavutil.py
This builds on the work by @IamPete1 in #995 and gets the generated javascript to pass tests, plus work in both a browser and in command line node tools
example usage: https://github.com/ArduPilot/WebTools/pull/265
also adds wss support to mavutil.py, so mavproxy can use wss: connections
=> allow javascript generator to work with both node and browser

tools/mavtranslatelog.py
This can be used to recover an existing `.tlog` file after introducing breaking changes in message definitions. For now it can handle changing the message id number, adding or removing fields, as long as the names don't change.
An example use case is when a custom dialect is requested to update the message ids into allocated range, like I needed to do in mavlink/mavlink#2272. This can be handled this way:
```sh
mavtranslatelog.py /path/to/old.tlog -f 5f24327765e5061acc3f17487ac12e441f067177 -F https://github.com/marsh-sim/mavlink.git -t dialect -T https://github.com/marsh-sim/mavlink.git
```
I do not know how often that happens in general (@hamishwillee may have comments?), thus whether it should be included in the package. If that's a small niche, no hard feelings if y'all prefer to …
=> tools: Add mavtranslatelog.py for updating tlog files

generator/mavschema.xsd
[new]
Adding a new consumption unit (L/h), that is better suited for large scale drones with Internal Combustion Engines.
Adding an already existing unit of volume litre "L". This is done to prevent breaking changes in various MAVLink CI runners that depend on unit definition using lower case "l" for the litre unit. Unit "l" is to be deprecated in the future.
=> [new] adding new unit of consumption: L/h

tests/snapshottests/__snapshots__/test_wlua.ambr, tests/snapshottests/resources/common.xml, tests/snapshottests/resources/minimal.xml, tests/snapshottests/resources/standard.xml
The Wireshark LUA test cases are using a relatively old snapshot of the Mavlink XML files. In order to make the tests more representative of today's XML, I have updated the snapshot files with the following:
common.xml, minimal.xml & standard.xml from: repo: mavlink/mavlink, commit: 33af200d
In particular, the tested XML now includes the MAV_BOOL enum/bitmask on various fields, which was what tripped up the parser to cause issue #1133 (fixed with #1134).
Given the XML changes, I believe the expected output changes make sense.:
* MAV_MODE_FLAG now used instead of MAV_MODE on MAV_CMD_DO_SET_MODE command.
* MAV_BOOL used for Arm param on MAV_CMD_COMPONENT_ARM_DISARM command.
* Addition fields added to MAV_PROTOCOL_CAPABILITY enum.
=> Mavgen WLua: Update Wireshark LUA test cases to use latest Mavlink XML
