generator/java/lib/Parser.java

The static member msg_received could be stomped from a second parser, which would cause a loss of one packet on one link. Removing it also corrected a logic failure reported in #43 by ixig

Java: Fix a race condition with a static member

---

setup.py

For justification, see https://github.com/ArduPilot/pymavlink/commit/d65275c29c57f11411fd7253b921471f973e1270#commitcomment-21865042

Home page is pymavlink, not mavlink

---

tools/mavkml.py

This adds a missing import to mavkml.py

mavkml.py uses os.path but did not import os

---

mavutil.py

Fixes https://github.com/ArduPilot/pymavlink/issues/77

Add missing PX4 modes

---

generator/mavgen_c.py

fix https://github.com/ArduPilot/mavlink/pull/45

mavgen_c.py: fix python3 message_name_array constructor

---

mavutil.py

compatible with dronekit-python

fix offboard mode

---

generator/maverrors.py

__sys__ is used on line 22 but is never imported.

import sys for line 22

---

generator/C/include_v2.0/mavlink_helpers.h
generator/C/include_v2.0/mavlink_sha256.h

fixing: https://github.com/mavlink/mavlink/issues/757

fix: mavlink_sha256.h sz type

---

.travis.yml
generator/mavgen.py
generator/mavschema.xsd
tools/mavgen.py

It validates that the units have no typos.

Add an enumeration restriction to validate the units attribute

---

README.md
__init__.py

fix https://github.com/ArduPilot/pymavlink/issues/153

Update web link for documentation

---

examples/README.md
examples/bwtest.py
examples/mavtest.py

Add a README.md to the examples folder, detailing what each example file does.
Add more comments to the bwtest.py and mavtest.py files.

Improve examples documentation

---

generator/mavschema.xsd

This is required by tridge/mavlink#8

Add units required by ESC_TELEMETRY_* messages

---

.travis.yml

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

travis: Add trailing space test in flake8

---

generator/mavschema.xsd

need for https://github.com/mavlink/mavlink/pull/1001

Generator: add mA units

---

generator/mavschema.xsd

This is a followup of #7 and goes together with mavlink/mavlink#623

Improve MAV_CMD parameter information

---

generator/mavschema.xsd

needed for weather station to report rain

Generator: add mm/h units for weather station

---

mavutil.py

using mcast URL, this allows for easier swarming setups

mavutil: support multicast UDP connections

---

mavutil.py

this separates out parameters and messages per source system, while
maintaining API compatibility with previous versions using attribute
properties

support multiple vehicle operation for mavutil

---

mavutil.py

Fix #255 
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

mavutil: Implement blocking for mavlogfile

---

generator/mavschema.xsd

Required for https://github.com/mavlink/mavlink/pull/1072

Add grams to SI_Units

---

generator/mavschema.xsd

Added MHz to SI_Units since needed here:
https://github.com/mavlink/mavlink/pull/1073

Add MHz to SI_Units

---

generator/mavgen_wlua.py

before:
after:
This PR allows the Wireshark dissector to correctly parse and display Mavlink 2.0 signatures.
Signatures are composed by 3 fields, link id, timestamp and signature itself. Link id and signature are shown in their numerical representation, while the timestamp is parsed and displayed accordingly to the user timezone.
This should be the last 2.0 feature missing from the Wireshark dissector.
Test packets have been generated with this ready-to-use script that makes use of [gomavlib](https://github.com/gswly/gomavlib) (replace 10.0.3.255 with a valid broadcast address):
```
( docker build - -t mav-emitter << EOF
FROM amd64/golang:1.11
WORKDIR /src
RUN echo 'module test' > go.mod
RUN echo '\n\
package main\n\
import (\n\
"time"\n\
"github.com/gswly/gomavlib"\n\ …
```

mavgen_wlua: support signature

---

tools/mavlogdump.py

mavlogdump.py: correct dumping out in CSV format

---

mavutil.py

This is going to help with Azure autotest running - actually it has been running for around a week without any more errors with TCP exceptions (and reboot is always detected).

Fix TCP reconnect issues

---

README.md

Update information about python3 support
Fix typo
remove duplicated gitter line

Add more information about what pymavlink is

---

tools/mavlogdump.py

Fixed a bug that causes the last line of the csv file output to be dropped.

Fix CSV file missing last line bug.

---

generator/mavschema.xsd

Requested for https://github.com/mavlink/mavlink/pull/1228. FYI @IamPete1

mavschema: Add support for cdeg/s angular rate

---

generator/CPP11/include_v2.0/msgmap.hpp

This patch fixes the aliasing bug mentioned in #365.
@tridge Please review.

CPP11 message serialisation aliasing fixed

---

generator/mavschema.xsd

generator: correct comment on rpm unit

---

tools/mavfft_isb.py

cope with corrupted frames where the fft length is truncated
print a pretty legend

mavfft_isb: minor improvements

---

generator/mavgen.py
generator/mavschema.xsd

so it will pass xml validation without error

Fixed 'bitmask' attribute definition 

---

generator/mavgen_c.py
generator/mavparse.py

this makes for more efficient code

mavgen: avoid packed C stuctures when not needed

---

generator/mavparse.py

this verbosity just made it harder to spot real issues

generator: removed old debug output

---

tools/mavfft_pid.py

tools: add mavfft_pid.py to allow FFT analysis for pids in log files

---

generator/mavgen_javascript.py

The javascript generator was not able to handle messages that contain arrays. This fixes the parsing of the incoming messages. The sending side is still not working.

mavgen: Javascript add parser array support

---

tools/mavfft_isb.py
tools/mavfft_pid.py

mavfft: correct sample rate on pids

---

DFReader.py

Give file position when a bad header or message is encountered
Check for zero length file

Make sure init_arrays() also observes 528 garbage skip

---

mavexpression.py
mavutil.py

use expression{condition}
example:
graph BATTERY_STATUS.current_battery*0.01{BATTERY_STATUS.id==0} BATTERY_STATUS.current_battery*0.01{BATTERY_STATUS.id==1}

mavexpression: support conditional expressions

---

tools/mavtomfile.py

Continued work from
https://github.com/ArduPilot/pymavlink/pull/435

This adds a conditional that prevents unicode values from being added as float values.

---

tools/mavfft_isb.py

This allows mavfft_isb to be invoked with the argument --notch-params and it will guess values for the harmonic notch based on the discovered peaks:
```
MacBook-Air:pymavlink andy$ ./tools/mavfft_isb.py --notch-params ~/Dropbox/Public/logs/Pre_Filter_User.bin 
Processing log /Users/andy/Dropbox/Public/logs/Pre_Filter_User.bin
.......................................................
55604s messages  74329 messages/second  4490477 kB/second
Extracted 208 fft data sets
Throttle average 0.227049
Sensor: Gyro[0]
Sensor: Accel[0]
Peaks: [ 39.01628017  81.93418837 120.95046854 159.96674871 241.90093708]
INS_HNTCH_REF = 0.2270
INS_HNTCH_FREQ = 39.0
INS_HNTCH_BW = 19.5
```

mavfft_isb: add support for calculation of harmonic notch parameters

---

mavutil.py

Supports https://github.com/ArduPilot/ardupilot/pull/15358/files

Add THERMAL mode for ArduPlane.

---

tools/mavkml.py

tools: mavkml: adjust shebang line to use Python from PATH

---

examples/min.js
examples/testparser.js
generator/C/test/posix/Makefile
generator/C/test/posix/testmav.c
generator/javascript/test/make_tests.py
generator/javascript/test/mavlink20.js
generator/javascript/test/message10.js
generator/javascript/test/message20.js
generator/mavgen_javascript.py

test suite also updated so passes
had to disable a couple of small spy.callCount. tests i don't quite understand yet, but given that this actually gets 400 additional SIGNING tests to actually pass, not just say they did, i say its a net positive.

Generator: JavaScript bindings , adding full support for mavlink2 signing, with tests.

---

generator/mavgen.py

this allows to include dialects from external folders
needed for https://github.com/mavlink/mavlink/pull/1537

use os.path.abspath() for inlcude files

---

test_gen_js.sh

hopefully will fix CI failure/s at https://github.com/mavlink/mavlink/actions/runs/499803504

generator: be explicit on where mavgen.py is for CI

---

README.md

As implemented in: https://github.com/ArduPilot/pymavlink/pull/468

README.md: Add documentation for custom mode map feature

---

generator/mavgen_javascript.py

https://github.com/mavlink/mavlink/pull/1531
The 'arguments' object , has special meaning in javascript, as it contains the values of the arguments passed to that function.... re-worked the generator to not use it, and use instead the ES6 compatible Rest parameters method.

generator: fix bug in Node/javascript exposed by a new 'events interface' pr

---

generator/mavschema.xsd

title says it
required for https://github.com/mavlink/mavlink/pull/1614

Add invalid attribute to mavschema

---

examples/mavtester.py

Get target component instead of target system

Bugfix accessing wrong property

---

mavutil.py

Supports https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/mode.h#L37-L38

Add SYSTEMID and AUTOROTATE modes for copter.

---

mavutil.py

https://github.com/ArduPilot/ardupilot/pull/18075

mavutil: add new AUTO_RTL mode 27 to copter

---

mavutil.py

Critical program breaking bug fixed

mavutil: fix docstring typo

---

mavwp.py

these items should "end" a mission sequence

mavwp: improve WP display after NAV_LAND and NAV_VTOL_LAND

---

mavutil.py

also fixes issue with ADSB adapter on CubeOrange

mavutil: fixed mode mapping with multiple vehicles

---

tools/magfit_WMM.py

This adds magfit support for the new param naming scheme in https://github.com/ArduPilot/ardupilot/pull/19490
Tested with current AP and built from that branch.

magfit_WMM: support new compass param naming

---

tools/mavlogdump.py

Co-authored-by: Peter Barker <pbarker@barker.dropbear.id.au>
Replaced https://github.com/ArduPilot/pymavlink/pull/434

mavlogdump.py: fix python2 deprecation

---

generator/mavgen_python.py

this makes it possible for pymavlink tools like MAVProxy to forward
unknown messages

mavgen: use MAVLink_unknown messages for unknown XML

---

mavutil.py

You end up with stringified byte strings in the log (`b"...."`) rather than binary data....
Both Py2 and Py3 tested, raw and tlog

mavutil.py: fix logfile handling under Python3

---

.github/workflows/test.yml
generator/C/include_v2.0/mavlink_get_info.h
generator/C/test/posix/Makefile
generator/C/test/posix/testmav.c
test_gen_js.sh
test_generator.sh

- fixed infinite loop in bisection search
- added test suite

C: fixed bug in mavlink_get_message_info_by_id

---

__init__.py
setup.py

allows scripts to test for pymavlink version

allow for print(pymavlink.__version__)

---

DFReader.py

use a dictionary of sets to record which instances of a message have
been seen before. This avoids us having to parse all instance based
messages fully during the load.
as we have added more instance messages the time to load the log has
become progressively longer. With this change it now becomes short
again
on a recent 160MByte quadplane log the time to load the log with this
change drops from 39.9s to 6.5s

speed up parsing of bin logs

---

tools/mavmsgstats.py

existing code is just indented, should be unchanged

mavmsgstats.py: add capability to parse tlogs

---

mavutil.py

this allows for graphing NAMED_VALUE_FLOAT properly with mavproxy and MAVExplorer from tlogs

mavutil: handle instances as strings in tlogs

---

DFReader.py

thanks to @IamPete1 for pointing out misunderstanding

DFReader: fixed defaults handling

---

generator/C/include_v1.0/mavlink_helpers.h
generator/C/include_v2.0/mavlink_helpers.h

Generator C: remove set but not used variable

---

mavutil.py

allows for SiK and RFD900x firmware update via flight controller with py3

mavutil: fixed MavlinkSerialPort wrapper for python3

---

tools/magfit_WMM.py

adds a per-iteration callback for the least-squares routine

tools: print progress in magfit_WMM

---

generator/mavgen.py
generator/mavparse.py

ensure we do not reference an enum that does not exist

mavgen: check for missing enums

---

generator/mavgen_lua.py
test_generate_all.sh

fixes issues pointed out by @rotu here https://github.com/ArduPilot/pymavlink/pull/791

Fix mavlink Lua Generator for ardupilot lua comments and add it to test script

---

DFReader.py

add close method that closes the open file DFReader_binary to address issue #844

add close method to binary reader

---

mavutil.py

@rmackay9: Discovered this whilst testing Quicktune.

mavutil: Add circle mode for rover

---

DFReader.py

allows correct mode mapping when version string is modified for custom build

DFReader: recognise VER.BU for build type

---

mavparm.py

ArduPilot sprouted some param defaults files which have 0x values in them.
This patch allows MAVProxy to `param load` these default files.

mavparm: allow param load of files containing 0x hex values

---

mavparm.py

this fixes param revert in MAVProxy

mavparm: fixed mavset with float

---

mavextra.py

tools have moved on and can just send in the correct data

mavextra.py: don't skip data for cores other than 0

---

DFReader.py

```
1970-01-01 10:00:04.00: FMT {Type : 128, Length : 89, Name : FMT, Format : BBnNZ, Columns : Type,Length,Name,Format,Columns}
1970-01-01 10:00:04.00: FMT {Type : 115, Length : 44, Name : FMTU, Format : QBNN, Columns : TimeUS,FmtType,UnitIds,MultIds}
1970-01-01 10:00:04.00: FMTU {TimeUS : 4009682, FmtType : 115, UnitIds : s---, MultIds : F---}
1970-01-01 10:00:04.00: FMTU {TimeUS : 4009680, FmtType : 128, UnitIds : -b---, MultIds : -----}
1970-01-01 10:00:04.00: FMT {Type : 59, Length : 75, Name : MSG, Format : QZ, Columns : TimeUS,Message}
1970-01-01 10:00:04.00: FMTU {TimeUS : 4009684, FmtType : 59, UnitIds : s-, MultIds : F-}
1970-01-01 10:00:04.00: MSG {TimeUS : 4009556, Message : Start 2}
1970-01-01 10:00:04.00: FMT {Type : 254, Length : 15, Name : TYPn, Format : Qn, Columns : …
```

DFReader: add support for float16 in BIN files

---

mavwp.py

…to" edge
stops showing us flying to these edges
changes the colour to match the label colour
Before:
After:
Before:
After:

mavwp: display DO_LAND_START paths as different edge colours and no "to" edge

---

mavutil.py

Closes #1009 
tested with
from pymavlink import mavutil
connection_str = "localhost:9876"
mavutil.mavlink_connection(connection_str,
dialect="minimal")

mavutil.py: work with minimal.xml

---

generator/mavgen_python.py
generator/mavparse.py

... also add a sanity check that the bitmask values are valid - which fails on a lot of XML at the moment

Add .bitmask attribute to enumerations

---

DFReader.py
dfindexer/dfindexer.c
dfindexer/dfindexer.h
dfindexer/dfindexer_cy.pyx

DFReader bugfix

---

DFReader.py

Not a blocker. This is a bug I noticed a long time ago, but never got around to fixing. FMT messages get the wrong timestamp if you scan a log and then rewind and parse again.
This bug used to be a lot worse, because the init_clock scanned through to the first GPS message and then exited, so FMT messages got that time. Now, on modern AP logs anyway, init_clock ends immediately after parsing a message containing the first TimeUS.
Anyway, `rewind()` should cause our clock's timestamp to go back to the time-of-first-timeus.
Tested before and after to confirm the bug and the fix.

DFReader: add rewind_event to DFReaderClock_usec

---

mavftp.py

Upstream port of https://github.com/ArduPilot/MethodicConfigurator/pull/45

mavftp: increase idle detection time

---

.github/workflows/pylint.yml
.github/workflows/python-publish.yml
.github/workflows/test.yml
README.md
generator/swift/Tests/ardugen.sh

also use "python3 -m pip" rather than just "pip"

Correct Python3 invocations to python3 not python

---

mavutil.py

this allows for ws:a.b.c.d:port for connecting to a websocket MAVLink server

mavutil: support ws:host:port for websocket client

---

tools/mavlogdump.py

added --show-loss to mavlogdump.py

mavlogdump: make it easier to find cause of lost messages

---

generator/mavgen_python.py

ensure we update the signature timestamp on each packet
fixes #961

mavgen_python: fixed signature timestamp update

---

DFReader.py

this keeps the speedup for fast indexing, while still properly indexing the more complex messages which have string instance IDs
It can still miss messages, but it will be rare

DFReader: fixed instance indexing for most messages

---

setup.py

and build without fast indexing if not

setup: detect if python dev package is installed

---

mavutil.py

mavutil: port field is reserved

---

generator/C/include_v2.0/mavlink_helpers.h

allow the signing timestamp limit to be set
